Repository sparc-request/sparc-request, pull requests merged in 2018-11, with the labels that each got.

#1588 KG - SPARC Proper Error Improvement
  app/controllers/application_controller.rb
  app/controllers/dashboard/base_controller.rb
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/dashboard/study_type_answers_controller.rb
  app/controllers/protocols_controller.rb
  app/controllers/service_requests_controller.rb
  app/models/protocol.rb
  app/models/service_request.rb
  app/views/service_requests/protocol.html.haml
  app/views/service_requests/protocol/_protocol_display.html.haml
  app/views/service_requests/service_details.html.haml
  app/views/service_requests/service_details/_details_dates.html.haml
  config/locales/en.yml
  spec/factories/service_request.rb
  spec/features/protocol/user_selects_publish_in_epic_spec.rb
Labels: MUSC, enhancement, refactors, version 3.4.0

#1589 KG - Homepage Calendar Improvements
  app/assets/stylesheets/proper/service_catalog.sass
  app/controllers/service_requests_controller.rb
  app/lib/news_feed/api_adapter.rb
  app/lib/news_feed/atlassian_adapter.rb
  app/lib/news_feed/page_parser.rb
  app/views/catalogs/_calendar.html.haml
  app/views/catalogs/_catalog_center.html.haml
  app/views/catalogs/_news.html.haml
  config/application.yml.example
  config/defaults.json
  config/locales/proper.en.yml
  config/schedule.rb
  doc/multi_institutional_documentation.md
Labels: MUSC, enhancement, version 3.4.0

#1591 KG - New Service Request Report Fields
  app/reports/protocols.rb
  app/reports/service_requests.rb
Labels: MUSC, enhancement, version 3.4.0

#1592 KG - Submission Emails Conditional Funding Source
  app/views/notifier/_protocol_information.html.haml
  config/locales/en.yml
  spec/mailers/notifier/get_a_cost_estimate_spec.rb
  spec/mailers/notifier/submitted_spec.rb
  spec/support/emails/tables.rb
Labels: MUSC, enhancement, version 3.4.0

#1593 SJ - ML - CM tree rights
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/stylesheets/catalog_manager/catalog.sass
  app/controllers/catalog_manager/catalog_controller.rb
  app/controllers/catalog_manager/organizations_controller.rb
  app/controllers/catalog_manager/services_controller.rb
  app/views/catalog_manager/catalog/_accordion.html.haml
  app/views/catalog_manager/catalog/_accordion_edit_link.html.haml
  app/views/catalog_manager/catalog/_core_accordion.html.haml
  app/views/catalog_manager/catalog/_program_accordion.html.haml
Labels: MUSC, enhancement, refactors, version 3.4.0

#1594 KG - Limit Orgs to 3 Primary Contacts
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/views/catalog_manager/organizations/_user_rights_row.html.haml
  app/views/catalog_manager/organizations/edit.js.coffee
  config/locales/catalog_manager.en.yml
  spec/features/catalog_manager/organization_forms/user_rights/user_manages_service_providers_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1596 KG - Catalog / Search Service Details + Pricing
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/javascripts/protocol.js.coffee
  app/assets/stylesheets/bootstrap-custom.sass
  app/assets/stylesheets/catalog_manager/catalog.sass
  app/assets/stylesheets/layout.sass
  app/assets/stylesheets/proper/protocols.sass
  app/assets/stylesheets/proper/service_catalog.sass
  app/assets/stylesheets/twitter_typeahead.sass
  app/controllers/catalogs_controller.rb
  app/controllers/search_controller.rb
  app/helpers/services_helper.rb
  app/models/pricing_map.rb
  app/models/service.rb
  app/reports/service_pricing_report.rb
  app/views/catalog_manager/pricing_setups/_pricing_setup_form.html.haml
  app/views/catalogs/_description.html.haml
  app/views/catalogs/accordion/_cores.html.haml
  app/views/catalogs/accordion/_services.html.haml
  app/views/service_requests/protocol/_service.html.haml
  app/views/service_requests/protocol/_service_list.html.haml
  spec/features/catalog/user_adds_service_spec.rb
  spec/features/catalog/user_begins_request_spec.rb
  spec/features/catalog_manager/accordion/user_searches_accordion_spec.rb
  spec/features/dashboard/protocols/user_should_no_longer_see_request_approve_services_spec.rb
  spec/features/dashboard/protocols/user_should_see_rm_id_displayed_spec.rb
  spec/features/document_management/user_returns_to_catalog_spec.rb
  spec/features/protocol/user_adds_authorized_user_spec.rb
  spec/features/protocol/user_creates_project_spec.rb
  spec/features/protocol/user_creates_study_spec.rb
  spec/features/protocol/user_deletes_authorized_user_spec.rb
  spec/features/protocol/user_edits_authorized_user_spec.rb
  spec/features/protocol/user_edits_protocol_spec.rb
  spec/features/protocol/user_edits_study_phases.rb
  spec/features/protocol/user_returns_to_catalog_spec.rb
  spec/features/protocol/user_selects_publish_in_epic_spec.rb
  spec/features/protocol/user_views_protocol_details_spec.rb
  spec/features/service_details/user_returns_to_catalog_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1597 KG - Protocol Filter Search by Email
  app/models/protocol.rb
  spec/features/dashboard/protocols/index/filters/admin_user_filters_my_admin_protocols_with_search_spec.rb
  spec/features/dashboard/protocols/index/filters/admin_user_filters_my_protocols_with_search_spec.rb
  spec/features/dashboard/protocols/index/filters/general_user_filters_with_search_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1598 KG - Order Pricing Setups/Maps in Descending Order
  app/views/catalog_manager/organizations/_pricing_form.html.haml
  app/views/catalog_manager/services/_pricing_form.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1599 KG - Change eIRB Date Data Type
  db/migrate/20181025193140_change_human_subject_eirb_dates.rb
  db/schema.rb
Labels: MUSC, enhancement, version 3.4.0

#1600 KG - Authorized User ORCID
  app/assets/javascripts/associated_users_form.js.coffee
  app/controllers/associated_users_controller.rb
  app/controllers/dashboard/associated_users_controller.rb
  app/helpers/associated_users_helper.rb
  app/models/identity.rb
  app/views/associated_users/_user_form.html.haml
  config/environments/development.rb
  config/locales/en.yml
  db/migrate/20181025132825_add_orcid_to_identities.rb
  db/schema.rb
Labels: MUSC, enhancement, version 3.4.0

#1602 Migration bug [#161398312]
  config/defaults.json
Labels: LA CaTS, bug, version 3.4.0

#1605 Config Improvement [#161554164]
  config/environments/production.rb
  config/environments/staging.rb
Labels: LA CaTS, security, version 3.4.0

#1608 KG - Form Question Dependent Bug
  app/helpers/surveyor/responses_helper.rb
  app/models/question_response.rb
  app/views/surveyor/responses/form/_response_question.html.haml
Labels: MUSC, bug, version 3.4.0

#1609 KG - Hide Service Components if Organization Not Selected for Fulfillment
  app/views/catalog_manager/services/_form.html.haml
  spec/factories/organization.rb
  spec/features/catalog_manager/accordion/user_views_organization_spec.rb
  spec/features/catalog_manager/organization_forms/associated_surveys/user_adds_associated_survey_to_table_spec.rb
  spec/features/catalog_manager/organization_forms/associated_surveys/user_removes_associated_survey_spec.rb
  spec/features/catalog_manager/organization_forms/fulfillment_rights/user_adds_identity_to_table_spec.rb
  spec/features/catalog_manager/organization_forms/fulfillment_rights/user_manages_clinical_providers_spec.rb
  spec/features/catalog_manager/organization_forms/fulfillment_rights/user_removes_identity_from_table_spec.rb
  spec/features/catalog_manager/organization_forms/general_information/user_edits_general_info_spec.rb
  spec/features/catalog_manager/organization_forms/pricing/user_adds_new_pricing_setup_spec.rb
  spec/features/catalog_manager/organization_forms/pricing/user_edits_pricing_setup_dates_and_source_spec.rb
  spec/features/catalog_manager/organization_forms/pricing/user_edits_pricing_setup_funding_source_rates_spec.rb
  spec/features/catalog_manager/organization_forms/pricing/user_edits_pricing_setup_percent_of_fee_spec.rb
  spec/features/catalog_manager/organization_forms/pricing/user_edits_subsidy_map_spec.rb
  spec/features/catalog_manager/organization_forms/pricing/user_uses_increase_decrease_modal_spec.rb
  spec/features/catalog_manager/organization_forms/status_options/user_manages_available_statuses_spec.rb
  spec/features/catalog_manager/organization_forms/status_options/user_manages_default_statuses_toggle_spec.rb
  spec/features/catalog_manager/organization_forms/status_options/user_manages_editable_statuses_spec.rb
  spec/features/catalog_manager/organization_forms/submission_emails/user_adds_submission_emails_spec.rb
  spec/features/catalog_manager/organization_forms/submission_emails/user_removes_submission_emails_spec.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_adds_identity_to_table_spec.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_manages_catalog_managers_spec.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_manages_service_providers_spec.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_manages_super_users_spec.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_removes_identity_from_table_spec.rb
  spec/features/catalog_manager/service_forms/components/user_adds_new_component_spec.rb
  spec/features/catalog_manager/service_forms/components/user_removes_component_spec.rb
  spec/features/service_subsidy/user_deletes_pending_subsidy_spec.rb
  spec/features/service_subsidy/user_edits_pending_subsidy_spec.rb
  spec/features/service_subsidy/user_requests_subsidy_spec.rb
  spec/features/service_subsidy/user_views_approved_subsidy_spec.rb
  spec/support/fixtures.rb
  spec/views/catalog_manager/services/_form.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1610 KG - Conditionally Hide Clinical/Non-Clinical Services Content for Admins
  app/models/organization.rb
  app/models/sub_service_request.rb
  app/views/dashboard/sub_service_requests/show.html.haml
  app/views/service_requests/request_report.xlsx.axlsx
  spec/features/dashboard/admin_edit/admin_edits_service_calendar_fields_spec.rb
  spec/features/dashboard/admin_edit/admin_interacts_with_template_tab_spec.rb
  spec/features/dashboard/protocols/index/requests_modal_spec.rb
  spec/features/dashboard/protocols/show/service_request_list_spec.rb
  spec/views/dashboard/sub_service_requests/_per_patient_per_visit.html.haml_spec.rb
  spec/views/dashboard/sub_service_requests/show.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1611 KG - Model/Table Cleanup
  app/assets/javascripts/catalog_manager/application.js
  app/assets/javascripts/dashboard/application.js
  app/assets/javascripts/jquery.toastmessage.js
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/catalog_manager/application.scss
  app/assets/stylesheets/dashboard/application.scss
  app/assets/stylesheets/jquery.toastmessage.css
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/models/identity.rb
  app/models/toast_message.rb
  config/locales/en.yml
  db/migrate/20181030190152_remove_unused_tables.rb
  db/schema.rb
  spec/controllers/dashboard/sub_service_requests/delete_destroy_spec.rb
  spec/factories/toast_message.rb
  spec/models/audited_spec.rb
Labels: MUSC, refactors, version 3.4.0

#1613 KG - Consolidated Corporate Study Request Fixes
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: bug, enhancement, version 3.4.0

#1614 JM - (SPARCDashboard & SPARCFulfillment) Go to Fulfillment Button Error Message
  app/api/v1/entities/full.rb
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/models/sub_service_request.rb
  config/locales/dashboard.en.yml
  db/migrate/20181029150447_add_imported_to_fulfillment_flag_to_ssr.rb
  spec/factories/sub_service_request.rb
  spec/views/dashboard/sub_service_requests/_header.html.haml_spec.rb
Labels: MUSC, version 3.4.0

#1585 KG - Add Back Tableau Settings
  app/views/catalogs/_tableau.html.haml
  config/application.yml.example
  config/defaults.json
  doc/multi_institutional_documentation.md
Labels: MUSC, bug, version 3.4.0

#1587 KG - Epic Queue Pagination
  app/assets/javascripts/surveyor/responses.js.coffee
  app/controllers/dashboard/epic_queue_records_controller.rb
  app/controllers/dashboard/epic_queues_controller.rb
  app/helpers/dashboard/epic_queues_helper.rb
  app/models/epic_queue.rb
  app/models/epic_queue_record.rb
  app/views/dashboard/epic_queue_records/index.json.jbuilder
  app/views/dashboard/epic_queues/_auth_user_change_list.html.haml
  app/views/dashboard/epic_queues/_epic_queue_records_table.html.haml
  app/views/dashboard/epic_queues/_epic_queues_table.html.haml
  app/views/dashboard/epic_queues/index.json.jbuilder
Labels: MUSC, bug, enhancement, version 3.4.0

#1617 ml-view_consolidated_req_dropdown_bug
  app/views/dashboard/service_requests/_service_requests.html.haml
Labels: bug, version 3.4.0

#1618 SJ - Reworking Guarantor fields
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/protocols_controller.rb
  app/models/protocol.rb
  app/views/dashboard/protocols/form/study_form_sections/_financial_information.html.haml
  app/views/protocols/form/study_form_sections/_financial_information.html.haml
  config/locales/en.yml
  db/migrate/20181107152300_change_guarantor_fields.rb
  db/schema.rb
  spec/api/v1/protocols/get_protocol_spec.rb
  spec/api/v1/protocols/get_protocols_spec.rb
  spec/api/v1/protocols/get_protocols_with_ids_spec.rb
  spec/factories/protocol.rb
Labels: MUSC, version 3.4.0

#1619 KG - Settings Populator Migration
  db/migrate/20181107162157_populate_v340_settings.rb
  db/schema.rb
Labels: MUSC, version 3.4.0

#1620 KG - Limit Primary Contact Bugs
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/views/catalog_manager/organizations/refresh_user_rights_row.js.coffee
  app/views/catalog_manager/organizations/remove_user_rights_row.js.coffee
Labels: MUSC, bug, version 3.4.0

#1621 KG - Pricing Setup/Map Collapses
  app/views/catalog_manager/organizations/_pricing_form.html.haml
  app/views/catalog_manager/services/_pricing_form.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1622 KG - Service Catalog Service Details Changes
  app/assets/javascripts/cart.js.coffee
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/stylesheets/layout.sass
  app/assets/stylesheets/proper/service_catalog.sass
  app/assets/stylesheets/twitter_typeahead.sass
  app/controllers/search_controller.rb
  app/helpers/services_helper.rb
  app/views/catalogs/accordion/_services.html.haml
  app/views/service_requests/right_navigation/_cart.html.haml
  app/views/service_requests/right_navigation/_cart_sub_service_request.html.haml
  app/views/service_requests/right_navigation/_cart_sub_service_requests.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1623 KG - Broken LDAP/Directory.rb
  app/lib/directory.rb
  app/models/setting.rb
  config/ldap.yml.example
Labels: MUSC, bug, version 3.4.0

#1624 KG - Note Bugs
  app/helpers/notes_helper.rb
  app/views/service_calendars/master_calendar/otf/_otf_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
Labels: MUSC, bug, version 3.4.0

#1626 KG - LDAP Filter Fix
  app/lib/directory.rb
Labels: MUSC, bug, version 3.4.0

#1627 ml-changes_to_Catalog_verbiage
  config/locales/catalog_manager.en.yml
Labels: bug, version 3.4.0

#1628 canned report output file name improvement [#61453314]
  app/controllers/reports_controller.rb
Labels: LA CaTS, enhancement, version 3.4.0

#1629 KG - Export Consolidated Arm Name Reference
  app/models/arm.rb
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.4.0

#1630 KG - Fix Catalog Pricing Styling
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/stylesheets/twitter_typeahead.sass
  app/helpers/services_helper.rb
  app/views/catalogs/accordion/_services.html.haml
Labels: MUSC, bug, version 3.4.0
