Repository sparc-request/sparc-request, pull requests merged in 2018-10, with the labels that each got.

#1574 KG - Settings Updates + YAML Storage
  app/lib/settings_populator.rb
  config/application.yml.example
  config/defaults.json
  config/epic.yml.example
  config/ldap.yml.example
  config/settings/api.json
  config/settings/application.json
  config/settings/calendar.json
  config/settings/cwf.json
  config/settings/epic.json
  config/settings/funding.json
  config/settings/ldap.json
  config/settings/news.json
  config/settings/oauth.json
  config/settings/right_navigation.json
  config/settings/rmid.json
  config/settings/system_satisfaction.json
  doc/multi_institutional_documentation.md
  spec/controllers/service_requests/get_catalog_spec.rb
  spec/features/catalog/provider_adds_short_interaction_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1572 KG - Copy Survey Issues
  app/assets/javascripts/surveyor/surveys.js.coffee
  app/assets/stylesheets/surveyor/surveys.sass
  app/models/survey.rb
Labels: MUSC, bug, version 3.4.0

#1575 Password reset email changes [#194911139]
  .env.example
  app/views/devise/mailer/reset_password_instructions.html.erb
  config/initializers/devise.rb
Labels: LA CaTS, bug, version 3.4.0

#1579 JM - SPARCDashboard (Report/Summary Readability)
  app/assets/stylesheets/service_calendar.sass
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_visit_input.html.haml
Labels: MUSC, version 3.4.0

#1580 JM - (SPARC-data) service_relations optional field improvement
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/services_controller.rb
  app/models/service.rb
  app/views/catalog_manager/services/_related_services_row.html.haml
  db/migrate/20181008141541_change_optional_to_required_for_related_services.rb
  lib/tasks/import_cores_and_services.rake
  spec/controllers/catalog_manager/services_controller_spec.rb
  spec/controllers/service_requests/post_add_service_spec.rb
  spec/controllers/service_requests/post_remove_service_spec.rb
  spec/factories/service_relation.rb
  spec/features/catalog_manager/service_forms/related_services/user_edits_service_relation_spec.rb
  spec/models/service_request_spec.rb
Labels: MUSC, version 3.4.0

#1581 JM - (SPARCRequest & SPARCDashboard) College Label Change
  lib/tasks/professional_org_name_change.rake
Labels: MUSC, version 3.4.0

#1584 KG - Services Searchable by EAP ID
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/stylesheets/bootstrap-custom.sass
  app/assets/stylesheets/catalog_manager/catalog.sass
  app/assets/stylesheets/proper/service_catalog.sass
  app/controllers/search_controller.rb
Labels: MUSC, enhancement, refactors, version 3.4.0

#1582 KG - News Feed Revamp
  app/controllers/service_requests_controller.rb
  app/lib/news_feed/api_adapter.rb
  app/lib/news_feed/atlassian_adapter.rb
  app/lib/news_feed/base.rb
  app/lib/news_feed/page_parser.rb
  config/application.yml.example
  config/defaults.json
  doc/multi_institutional_documentation.md
  spec/support/webmock.rb
Labels: MUSC, enhancement, version 3.4.0
