Repository sparc-request/sparc-request, pull requests merged in 2018-09, with the labels that each got.

#1528 KG - Can't View Responses With Certain Unanswered Questions
  app/views/surveyor/responses/form/form_partials/_checkbox_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_dropdown_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_likert_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_multiple_dropdown_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_radio_button_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_yes_no_form_partial.html.haml
Labels: MUSC, bug, cherry-pick, version 3.3.0

#1523 KG - SPARCForms Permissions
  app/controllers/surveyor/responses_controller.rb
  app/helpers/surveyor/responses_helper.rb
  app/models/system_survey.rb
  app/views/surveyor/responses/index.json.jbuilder
  spec/controllers/surveyor/responses/get_index_spec.rb
  spec/features/surveyor/responses/user_views_responses_table_spec.rb
  spec/helpers/surveyor/responses_helper_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1532 KG - Admin Approvals Label
  config/locales/dashboard.en.yml
Labels: MUSC, enhancement, version 3.4.0

#1533 KG - Consolidated Request NoMethod Error
  app/controllers/dashboard/protocols_controller.rb
Labels: MUSC, bug, version 3.4.0

#1534 KG - Question Answered Warning Alignment
  app/views/surveyor/surveys/form/_dependent_dropdown.html.haml
  app/views/surveyor/surveys/form/_survey_question.html.haml
Labels: MUSC, bug, version 3.4.0

#1535 KG - Update Table Charsets and Collation
  app/models/protocol.rb
  db/migrate/20180905143632_convert_tables_to_utf8.rb
  db/schema.rb
Labels: MUSC, bug, enhancement, version 3.4.0

#1541 KG - Add CPT Code to Services Dropdowns
  app/helpers/dashboard/study_level_activities_helper.rb
  app/views/dashboard/multiple_line_items/_add_line_items_form.html.haml
  app/views/dashboard/multiple_line_items/_remove_line_items_form.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1542 KG - Pull EIRB Dates from RMID
  app/api/v1/entities/full.rb
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/protocols_controller.rb
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/view_details/_research_involving.html.haml
  config/locales/en.yml
  db/migrate/20180910161245_add_human_subjects_initial_irb_approval_date.rb
  db/schema.rb
  lib/tasks/update_protocol_with_validated_rm.rake
Labels: MUSC, enhancement, version 3.4.0

#1543 KG - Form Builder Access Code Modal "Enter" Closes Modal
  app/views/surveyor/surveys/_new_form.haml
Labels: MUSC, bug, version 3.4.0

#1546 KG - Export Responses
  app/assets/javascripts/surveyor/responses.js.coffee
  app/controllers/surveyor/responses_controller.rb
  app/views/surveyor/responses/_table.html.haml
  app/views/surveyor/responses/index.xlsx.axlsx
  config/locales/surveyor.en.yml
Labels: MUSC, enhancement, version 3.4.0

#1547 KG - Improve Homepage Search Usability
  app/assets/stylesheets/proper/service_catalog.sass
  app/views/catalogs/_catalog_center.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1548 KG - SPARCForms Table Optimization
  app/helpers/surveyor/responses_helper.rb
  app/models/system_survey.rb
  app/views/surveyor/responses/index.json.jbuilder
  spec/helpers/surveyor/responses_helper_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1552 KG - Update Permissible Value Seed Docs
  doc/multi_institutional_documentation.md
Labels: MUSC, enhancement, version 3.4.0

#1554 KG - Ignore SettingsPopulator Logs in Test Suite
  app/lib/settings_populator.rb
Labels: MUSC, refactors, version 3.4.0

#1550 Save Falsy Setting Overrides from application.yml
  app/lib/default_settings_populator.rb
Labels: bug, version 3.3.0

#1556 KG - Export Consolidated Bugs
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.4.0

#1557 KG - 3.3.0 Settings Docs Updates & initial_cm_creation location
  CUSTOMIZE.md
  INSTALL.md
  doc/easy_installation.doc
  doc/easy_installation.pdf
  doc/multi_institutional_documentation.md
Labels: MUSC, enhancement, version 3.3.0

#1558 KG - Catalog Search Service Tooltip HTML
  app/assets/javascripts/catalog.js.coffee
Labels: MUSC, enhancement, version 3.4.0

#1559 KG - Add is_available to Permissible Value Seeds
  db/seeds/permissible_values/2.0.5/affiliation_types.csv
  db/seeds/permissible_values/2.0.5/document_types.csv
  db/seeds/permissible_values/2.0.5/federal_grant_codes.csv
  db/seeds/permissible_values/2.0.5/federal_grant_non_phs_sponsors.csv
  db/seeds/permissible_values/2.0.5/federal_grant_phs_sponsors.csv
  db/seeds/permissible_values/2.0.5/funding_sources.csv
  db/seeds/permissible_values/2.0.5/funding_statuses.csv
  db/seeds/permissible_values/2.0.5/impact_areas.csv
  db/seeds/permissible_values/2.0.5/potential_funding_sources.csv
  db/seeds/permissible_values/2.0.5/proxy_rights.csv
  db/seeds/permissible_values/2.0.5/statuses.csv
  db/seeds/permissible_values/2.0.5/study_types.csv
  db/seeds/permissible_values/2.0.5/submission_types.csv
  db/seeds/permissible_values/2.0.5/subspecialties.csv
  db/seeds/permissible_values/2.0.5/user_credentials.csv
  db/seeds/permissible_values/2.0.5/user_roles.csv
Labels: MUSC, enhancement, version 3.4.0

#1561 KG - Tags Improvements
  app/models/tag.rb
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
  spec/features/catalog_manager/organization_forms/general_information/user_edits_general_info_spec.rb
  spec/features/catalog_manager/service_forms/general_information/user_edits_general_info_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1562 KG - Audit Study Type Questions & Answers
  app/models/study_type_answer.rb
  app/models/study_type_question.rb
  db/migrate/20150112140439_add_request_uuid_to_audits.rb
Labels: MUSC, enhancement, version 3.4.0

#1563 KG - Retrieve Pro # From RMID
  app/assets/javascripts/protocol_form.js.coffee
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
  lib/tasks/update_protocol_with_validated_rm.rake
Labels: MUSC, enhancement, version 3.4.0

#1565 KG - Falsy Values in SettingsPopulator
  app/lib/settings_populator.rb
Labels: MUSC, enhancement, version 3.4.0

#1566 KG - eIRB Dates Import Task
  lib/tasks/import_historical_eirb_fields.rake
Labels: MUSC, enhancement, version 3.4.0

#1567 KG - Disable Auditing / Fix Migration from #1562
  db/migrate/20150326155450_create_study_type_questions.rb
  db/migrate/20151012140439_add_request_uuid_to_audits.rb
Labels: MUSC, refactors, version 3.4.0

#1568 KG - Hide Tags Select if No Tags Present
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1570 Jl - ssr view bug
  app/views/dashboard/sub_service_requests/_user_modal_ssr_show.html.haml
Labels: MUSC, bug, version 3.4.0

#1571 KG - Hide r/t Zeroes in Admin Edit Export
  app/views/service_requests/request_report.xlsx.axlsx
Labels: MUSC, enhancement, version 3.4.0
