Repository sparc-request/sparc-request, pull requests merged in 2018-05, with the labels that each got.

#1306 JM - (SPARCDashboard) Go to Fulfillment Link should Directly Link to the Corresponding Request Page
  app/helpers/dashboard/sub_service_requests_helper.rb
  spec/views/dashboard/sub_service_requests/_header.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.3.0

#1289 Add incomplete status to permissible_values table and update database [#156174417]
  db/migrate/20180320202055_add_incomplete_status_to_permissible_values.rb
Labels: LA CaTS, enhancement, version 3.3.0

#1299 JM - (SPARCForms) View Response Likert Bug
  app/assets/javascripts/likert.js.coffee
  app/views/surveyor/responses/form/_response_question.html.haml
  app/views/surveyor/responses/form/form_partials/_likert_form_partial.html.haml
  spec/features/review/user_views_system_satisfaction_survey_response_spec.rb
Labels: MUSC, version 3.3.0

#1301 Ability to specify multiple ldap_base for searching [#152927779]
  app/lib/directory.rb
  config/ldap.yml.example
  db/migrate/20180417172116_change_ldap_base_setting_to_json.rb
  db/schema.rb
Labels: MUSC, enhancement, version 3.3.0

#1302 JM- (SPARCForm) View Improvements: Add Submitted By, Add Link, Wrapping
  app/views/surveyor/responses/_table.html.haml
Labels: MUSC, version 3.3.0

#1303 Jl - epic queue record notes and excel export
  app/assets/stylesheets/dashboard/epic_queues.sass
  app/helpers/dashboard/epic_queues_helper.rb
  app/helpers/service_calendar_helper.rb
  app/models/epic_queue.rb
  app/models/epic_queue_record.rb
  app/views/dashboard/epic_queue_records/index.json.jbuilder
  app/views/dashboard/epic_queues/_epic_queue_records_table.html.haml
  app/views/notes/_new.html.haml
  app/views/notes/_table.html.haml
  app/views/notes/create.js.coffee
  config/locales/en.yml
Labels: MUSC, version 3.3.0

#1304 wth - (SPARCRequest & SPARCDashboard) Document Types (.PDF)
  app/models/document.rb
Labels: MUSC, version 3.3.0

#1307 Jl - Send to epic button bug
  app/views/dashboard/sub_service_requests/_request_details.html.haml
Labels: MUSC, bug, version 3.3.0

#1308 Add time stamp to uploaded column [#188974838]
  app/views/dashboard/documents/index.json.jbuilder
  app/views/documents/index.json.jbuilder
  app/views/funding/services/_documents.html.haml
  app/views/funding/services/documents.json.jbuilder
Labels: LA CaTS, enhancement, version 3.3.0

#1313 KG - Cents in Milestone Amount Fields
  app/assets/javascripts/global.js.coffee
  app/views/dashboard/protocols/_milestone.html.haml
  app/views/service_requests/service_details/_details_dates.html.haml
  db/migrate/20180503165457_migrate_protocol_amounts_to_integers.rb
  db/schema.rb
Labels: MUSC, enhancement, version 3.3.0

#1323 Jl - epic queue notes
  app/assets/javascripts/dashboard/application.js
  app/assets/javascripts/dashboard/tableExport.js
  app/assets/javascripts/tableExport.js
  app/views/notes/_index.html.haml
Labels: MUSC, enhancement, version 3.3.0

#1331 SJ - Removing all mentions of required forms tag [#156624050]
  app/lib/generate_request_grant_billing_pdf.rb
  app/mailers/notifier.rb
  config/locales/en.yml
  db/migrate/20140305162451_rename_muha_tag.rb
  db/migrate/20180524135959_remove_required_forms_tag.rb
  db/schema.rb
  doc/multi_institutional_documentation.md
Labels: MUSC, enhancement, version 3.3.0

#1322 KG - Devise Secret Key
  config/initializers/devise.rb
Labels: MUSC, Utah, enhancement, under review by OS committee

#1321 KG - Customize Time Zone With Dotenv
  .env.example
  config/application.rb
Labels: MUSC, Utah, enhancement, under review by OS committee

#1311 KG - Remove Surveys Display Order
  app/controllers/surveyor/surveys_controller.rb
  app/helpers/surveyor/surveys_helper.rb
  app/models/survey.rb
  app/models/system_survey.rb
  app/views/surveyor/surveys/form/_survey_fields.html.haml
  app/views/surveyor/surveys/index.html.haml
  app/views/surveyor/surveys/index.json.jbuilder
  db/migrate/20180503145651_remove_display_order_from_surveys.rb
  db/schema.rb
  spec/factories/form.rb
  spec/factories/survey.rb
  spec/factories/system_survey.rb
  spec/features/surveyor/surveys/user_edits_survey_fields_spec.rb
  spec/models/system_survey/system_survey_spec.rb
  spec/support/capybara_support.rb
Labels: MUSC, enhancement, version 3.3.0

#1312 KG - Update version when changing access code
  app/controllers/surveyor/survey_updater_controller.rb
  app/views/surveyor/survey_updater/update.js.coffee
  spec/features/surveyor/surveys/user_edits_survey_fields_spec.rb
Labels: MUSC, enhancement, version 3.3.0

#1318 KG - Response Table Header Styling
  app/assets/stylesheets/surveyor/responses.sass
Labels: MUSC, bug, version 3.3.0

#1327 Start and end dates label changes [#157257811}
  config/locales/dashboard.en.yml
  config/locales/proper.en.yml
Labels: LA CaTS, version 3.3.0

#1314 KG - Permissible Values is_available
  app/models/permissible_value.rb
  db/migrate/20170919210744_clean_up_first_draft_editable_statuses.rb
  db/migrate/20171012163715_add_flag_for_selected_available_and_editable_statuses.rb
  db/migrate/20180504190914_add_is_available_to_permissible_values.rb
  db/schema.rb
  spec/factories/permissible_value.rb
  spec/models/permissible_value_spec.rb
  spec/support/permissible_values.rb
Labels: MUSC, enhancement, version 3.3.0

#1319 KG - Milestone Budget Amounts Conversion
  app/models/protocol.rb
Labels: MUSC, bug, version 3.3.0
