Repository sparc-request/sparc-request, pull requests merged in 2018-03, with the labels that each got.

#1263 JM - (SPARC Script) Update All Protocol Info That Have Been Pushed to Epic
  lib/epic_interface.rb
  lib/tasks/update_protocol_info_pushed_to_epic.rake
Labels: MUSC, version 3.2.0

#1268 KG - Fix Dropdown Dependency Bug
  app/assets/javascripts/surveyor/responses.js.coffee
  app/views/surveyor/responses/form/form_partials/_dropdown_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_multiple_dropdown_form_partial.html.haml
  spec/features/surveyor/user_previews_survey_spec.rb
Labels: MUSC, bug, version 3.2.0

#1269 KG - Remove Associated Survey Bug
  app/controllers/catalog_manager/catalog_controller.rb
  spec/controllers/catalog_manager/catalog/post_remove_associated_survey_spec.rb
Labels: MUSC, bug, version 3.2.0

#1270 SJ - Fixes for export request
  app/models/protocol.rb
  app/views/dashboard/protocols/show.xlsx.axlsx
  app/views/dashboard/service_requests/_service_requests.html.haml
Labels: MUSC, bug, version 3.2.0

#1271 SJ - Additional fixes for export request
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, enhancement, version 3.2.0

#1272 JM- (SPARC Script) Update All Protocol Info That Have Been Pushed to Epic
  lib/epic_interface.rb
  lib/tasks/update_protocol_info_pushed_to_epic.rake
Labels: MUSC, version 3.2.0

#1276 KG - Fix SystemSurvey Display order Sorting
  app/models/system_survey.rb
  app/views/surveyor/surveys/index.html.haml
  spec/features/surveyor/user_edits_survey_fields_spec.rb
Labels: MUSC, bug, version 3.2.0

#1278 KG - Update Survey/Form Builder, SPARCForms Permissions
  app/controllers/surveyor/base_controller.rb
  app/controllers/surveyor/responses_controller.rb
  app/controllers/surveyor/surveys_controller.rb
  app/helpers/application_helper.rb
  app/models/form.rb
  app/models/identity.rb
  app/models/organization.rb
  app/models/response.rb
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/surveys/index.html.haml
  spec/controllers/surveyor/responses/get_index_spec.rb
  spec/controllers/surveyor/surveys/get_search_surveyables_spec.rb
  spec/controllers/surveyor/surveys/post_create_spec.rb
  spec/features/surveyor/user_filters_responses_spec.rb
  spec/features/surveyor/user_views_responses_table_spec.rb
  spec/models/form/for_spec.rb
Labels: MUSC, bug, version 3.2.0
