Repository sparc-request/sparc-request, pull requests merged in 2018-12, with the labels that each got.

#1642 KG - Add app/lib/reporting.rb
  app/lib/reports/reporting.rb
Labels: MUSC, bug, version 3.4.0

#1645 KG - Force WaitHelpers to wait until jQuery loaded on page
  spec/support/features/wait_helpers.rb
Labels: MUSC, bug, specs, version 3.4.0

#1640 KG - Add XVFB For Travis Feature Specs
  .travis.yml
Labels: MUSC, enhancement, version 3.4.0

#1583 KG - Org Name Validation
  app/models/organization.rb
  spec/features/catalog_manager/organization_forms/new_organization/user_creates_new_core_spec.rb
  spec/features/catalog_manager/organization_forms/new_organization/user_creates_new_institution_spec.rb
  spec/features/catalog_manager/organization_forms/new_organization/user_creates_new_program_spec.rb
  spec/features/catalog_manager/organization_forms/new_organization/user_creates_new_provider_spec.rb
Labels: MUSC, version 3.4.0

#1625 KG - User Mailer Protocol Funding Source
  app/views/user_mailer/_protocol_info_table.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1637 JM - (SPARCRequest Step 2 & SPARCDashboard) Study Information Switching Funding Status Bug
  app/assets/javascripts/protocol_form.js.coffee
Labels: MUSC, version 3.4.0

#1643 KG - Pricing Map/Setup Collapse Restyle
  app/assets/javascripts/catalog_manager/application.js
  app/assets/javascripts/global.js.coffee
  app/assets/stylesheets/catalog_manager/catalog.sass
  app/views/catalog_manager/organizations/_pricing_form.html.haml
  app/views/catalog_manager/services/_pricing_form.html.haml
  config/locales/en.yml
Labels: MUSC, enhancement

#1644 KG - Fix Settings Caching
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/setting.rb
  spec/support/settings.rb
Labels: MUSC, bug, enhancement, version 3.4.0

#1646 KG - Fix SPARCForms Permissions
  app/assets/stylesheets/surveyor/responses.sass
  app/helpers/surveyor/responses_helper.rb
  app/models/form.rb
  app/models/system_survey.rb
  app/views/surveyor/responses/index.json.jbuilder
Labels: MUSC, bug, version 3.4.0

#1647 KG - Export Consolidated Study Budget Arm Ref
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.4.0

#1648 KG - ORCID JavaScript Improvement
  app/assets/javascripts/associated_users_form.js.coffee
Labels: MUSC, bug, version 3.4.0

#1650 JM- hide patient registrar option
  app/views/catalog_manager/organizations/_fulfillment_rights_form.html.haml
  app/views/catalog_manager/organizations/_fulfillment_rights_row.html.haml
Labels: MUSC, version 3.4.0

#1638 AC / KG - Epic User Validation
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/associated_users_controller.rb
  app/controllers/dashboard/associated_users_controller.rb
  app/models/epic_user.rb
  app/views/associated_users/_user_form.html.haml
  config/defaults.json
  config/environment.rb
  config/locales/en.yml
  doc/multi_institutional_documentation.md
Labels: MUSC, cherry-pick, enhancement, version 3.4.0

#1649 KG - Spec Fixes
  spec/features/dashboard/protocols/edit/user_edits_epic_answers_spec.rb
  spec/features/dashboard/protocols/edit/user_edits_protocol_spec.rb
  spec/features/dashboard/protocols/edit/user_views_details_after_editing_epic_answers_spec.rb
  spec/features/dashboard/service_requests/user_views_ssrs_spec.rb
Labels: MUSC, specs, version 3.4.0

#1651 KG - More Service Details Updates
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/javascripts/global.js.coffee
  app/assets/stylesheets/catalog_manager/catalog.sass
  app/assets/stylesheets/proper/service_catalog.sass
  app/assets/stylesheets/twitter_typeahead.sass
  app/helpers/services_helper.rb
  app/views/catalog_manager/organizations/_pricing_form.html.haml
  app/views/catalog_manager/services/_pricing_form.html.haml
  app/views/catalogs/_calendar.html.haml
  app/views/catalogs/accordion/_services.html.haml
  config/locales/en.yml
  config/locales/proper.en.yml
  db/schema.rb
  spec/features/proper/happy_spec.rb
Labels: MUSC, enhancement, version 3.4.0

#1634 Access empty protocols [#161193400]
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/super_users_controller.rb
  app/controllers/dashboard/base_controller.rb
  app/models/protocol.rb
  app/views/catalog_manager/organizations/_user_rights_form.html.haml
  app/views/catalog_manager/organizations/_user_rights_row.html.haml
  config/locales/catalog_manager.en.yml
  config/routes.rb
  db/migrate/20181116193113_add_access_empty_protocols_to_super_users.rb
  spec/controllers/catalog_manager/super_users_controller_spec.rb
  spec/controllers/dashboard/base_controller_spec.rb
  spec/factories/super_user.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_manages_super_users_spec.rb
  spec/features/dashboard/protocols/edit/user_edits_epic_answers_spec.rb
  spec/features/dashboard/protocols/edit/user_edits_protocol_spec.rb
  spec/features/dashboard/protocols/edit/user_views_details_after_editing_epic_answers_spec.rb
  spec/features/dashboard/protocols/index/dashboard_index_spec.rb
  spec/features/dashboard/protocols/index/rmid_validated_protocol_spec.rb
Labels: LA CaTS, enhancement, version 3.4.0

#1653 JM - (SPARCDashboard & SPARCFulfillment) Go to Fulfillment Button Error Message
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
  app/assets/stylesheets/dashboard/admin_edit.sass
  app/assets/stylesheets/dashboard/application.scss
  app/helpers/dashboard/sub_service_requests_helper.rb
Labels: MUSC, version 3.4.0

#1652 SJ - Ruby version upgrade
  .ruby-version
  .ruby-version.example
  app/views/dashboard/documents/_document_form.html.haml
  app/views/dashboard/protocols/form/_protocol_form.html.haml
  app/views/dashboard/study_level_activities/_fulfillment_form.html.haml
  app/views/dashboard/study_level_activities/_sla_admin_rate_form.html.haml
  app/views/dashboard/study_level_activities/_study_level_activity_form.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1655 KG - Org Hierarchy Order Bug
  app/models/organization.rb
  app/models/service.rb
Labels: MUSC, bug, version 3.4.0

#1656 KG - More Service Catalog Style Updates
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/stylesheets/proper/service_catalog.sass
  app/helpers/services_helper.rb
  app/views/catalogs/accordion/_services.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1657 KG - Conditionally Show Epic EMR Access Column
  app/views/associated_users/_table.html.haml
  app/views/dashboard/associated_users/_table.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1659 KG - Step 3/4 Validation Changes
  app/controllers/service_requests_controller.rb
  app/views/service_requests/service_calendar.html.haml
  app/views/service_requests/service_details/_details_dates.html.haml
Labels: MUSC, bug, version 3.4.0

#1660 KG - More Service Details Styling
  app/assets/stylesheets/proper/service_catalog.sass
  app/helpers/services_helper.rb
  app/views/catalogs/accordion/_services.html.haml
Labels: MUSC, enhancement, version 3.4.0

#1661 KG - Forms Fixes
  app/controllers/forms_controller.rb
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/models/form.rb
  app/models/service_request.rb
  app/models/sub_service_request.rb
  db/schema.rb
  spec/controllers/forms/get_index_spec.rb
Labels: MUSC, bug, version 3.4.0

#1662 KG - Epic Queue Table Search
  app/controllers/dashboard/epic_queue_records_controller.rb
  app/controllers/dashboard/epic_queues_controller.rb
  app/models/epic_queue.rb
  app/models/epic_queue_record.rb
Labels: MUSC, bug, version 3.4.0

#1663 KG - Epic Queue Protocol Link Bug
  app/assets/javascripts/dashboard/epic_queues.js.coffee
  app/views/dashboard/epic_queue_records/index.json.jbuilder
  app/views/dashboard/epic_queues/index.json.jbuilder
Labels: MUSC, bug, version 3.4.0

#1664 KG - eIRB Validated Form Logic
  app/assets/javascripts/protocol_form.js.coffee
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
Labels: MUSC, bug, version 3.4.0

#1665 KG - eIRB Data Import Task Improvements
  db/schema.rb
  lib/tasks/import_historical_eirb_fields.rake
Labels: MUSC, enhancement, version 3.4.0

#1666 KG - Disable eIRB Fields on Edit if eIRB Validated
  app/models/protocol.rb
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
Labels: MUSC, bug, version 3.4.0

#1667 KG - Fix eIRB Import Task
  lib/tasks/import_historical_eirb_fields.rake
Labels: MUSC, enhancement, version 3.4.0

#1668 KG - Pre-populate RMID Data When Editing Protocol
  app/assets/javascripts/protocol_form.js.coffee
  app/models/protocol.rb
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
  config/defaults.json
Labels: MUSC, enhancement, version 3.4.0

#1669 SJ - Quick fix for service model
  app/models/arm.rb
  app/models/identity.rb
  app/models/line_item.rb
  app/models/line_items_visit.rb
  app/models/organization.rb
  app/models/protocol.rb
  app/models/question.rb
  app/models/service.rb
  app/models/service_request.rb
  app/models/sub_service_request.rb
  app/models/survey.rb
  app/models/visit_group.rb
Labels: MUSC, bug, version 3.4.0
