Repository sparc-request/sparc-request, pull requests merged in 2018-06, with the labels that each got.

#1333 fix to LIV subject counts of zero being updated on submit [#157736871]
  app/models/arm.rb
Labels: version 3.3.0

#1335 Add refresh icon on Application/LOI buttons [#157681633]
  app/assets/javascripts/funding/documents.js.coffee
  app/views/funding/services/_documents.html.haml
Labels: LA CaTS, enhancement, version 3.3.0

#1337 Rate on dashboard for OTF was displaying direct cost total [#157938291]
  app/helpers/dashboard/study_level_activities_helper.rb
  app/models/line_item.rb
Labels: version 3.3.0

#1341 wth - (SPARCRequest & SPARCDashboard) Milestone decimal fix
  db/migrate/20180604172404_convert_ints_to_big_ints.rb
Labels: MUSC, bug, version 3.3.0

#1342 wth - (SPARCRequest) Rails 5.2 Updates
  Gemfile
  Gemfile.lock
  bin/bundle
  bin/setup
  bin/update
  bin/yarn
  config/boot.rb
  config/cable.yml
  config/initializers/application_controller_renderer.rb
  config/initializers/content_security_policy.rb
  config/initializers/cookies_serializer.rb
  config/initializers/new_framework_defaults_5_2.rb
  config/puma.rb
  config/spring.rb
  config/storage.yml
Labels: MUSC, version 3.3.0

#1345 ml - removed parens for consistency
  config/locales/dashboard.en.yml
  config/locales/proper.en.yml
Labels: version 3.3.0

#1347 wth - (SPARCForm) Response View Filters
  app/controllers/surveyor/response_filters_controller.rb
  db/migrate/20180606180011_change_datetime_to_strings.rb
  spec/controllers/surveyor/response_filters/get_new_spec.rb
  spec/controllers/surveyor/response_filters/post_create_spec.rb
  spec/factories/response_filter.rb
  spec/features/surveyor/responses/user_clicks_saved_filter_spec.rb
  spec/features/surveyor/responses/user_saves_filter_spec.rb
Labels: MUSC, bug, version 3.3.0

#1355 Admins can edit units per quantity in dashboard [#158158339]
  app/models/line_item.rb
  app/views/dashboard/study_level_activities/_study_level_activity_form.html.haml
  app/views/service_calendars/master_calendar/otf/_otf_line_items.html.haml
  config/locales/dashboard.en.yml
Labels: version 3.3.0

#1364 wth - Dashboard::LineItemsVisitsController
  app/controllers/dashboard/line_items_controller.rb
  spec/controllers/dashboard/line_items/delete_destroy_spec.rb
Labels: version 3.3.0

#1370 Fix Save as Draft bug when editing a SSR [#151738929 ]
  app/views/service_requests/modals/_save_as_draft_modal.html.haml
  app/views/service_requests/save_and_exit.js.coffee
Labels: LA CaTS, bug, version 3.3.0

#1376 Jl - Approval timestamp bug
  app/models/sub_service_request.rb
Labels: MUSC, bug, version 3.3.0

#1346 Jl - Move visit validation
  app/controllers/service_calendars_controller.rb
  app/views/service_calendars/_move_visits_modal.haml
  app/views/service_calendars/move_visit_position.js.coffee
  spec/controllers/service_calendars/post_move_visit_position_spec.rb
Labels: MUSC, bug, version 3.3.0

#1359 Ability to have recurring events [#157608038]
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/proper/service_catalog.sass
  app/controllers/application_controller.rb
  app/controllers/service_requests_controller.rb
Labels: version 3.3.0

#1329 Jtm migration for bigints
  app/models/study_type_answer.rb
  app/models/subsidy.rb
  db/migrate/20171106161235_change_ids_from_int_to_bigint.rb
  lib/tasks/migrate_ids_to_bigint.rake
Labels: version 3.3.0

#1326 KG - Update Proxy Rights Label
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.3.0

#1384 Adding documents back in to see why this would be breaking
  app/models/permissible_value.rb
  lib/tasks/migrate_ids_to_bigint.rake
Labels: version 3.3.0

#1385 News feed issues cause the catalog page to hang up
  app/controllers/service_requests_controller.rb
  app/views/catalogs/_news.html.haml
Labels: version 3.3.0

#1388 Updating col header generation to allow for any number of columns
  app/views/service_requests/coverage_analysis.xlsx.axlsx
  config/initializers/worksheet.rb
Labels: version 3.3.0

#1399 KG - Fix Viewport Width
  app/assets/stylesheets/layout.sass
  app/assets/stylesheets/proper/layout.sass
Labels: MUSC, bug, version 3.3.0
