Repository sparc-request/sparc-request, pull requests merged in 2018-07, with the labels that each got.

#1396 fixed sort Created column bug [#158665905]
  app/views/funding/services/index.html.haml
Labels: LA CaTS, bug, version 3.3.0

#1404 KG - View Response Likert Bug
  app/assets/javascripts/likert.js.coffee
  app/views/surveyor/responses/form/_response_question.html.haml
  app/views/surveyor/responses/form/form_partials/_likert_form_partial.html.haml
  spec/features/review/user_views_system_satisfaction_survey_response_spec.rb
Labels: MUSC, bug, version 3.3.0

#1414 Jl - form functionality validation
  app/helpers/surveyor/surveys_helper.rb
  app/models/survey.rb
  app/views/surveyor/surveys/form/_survey_question.html.haml
  config/locales/surveyor.en.yml
Labels: MUSC, enhancement, version 3.3.0

#1398 KG - Response Filter Updates
  app/assets/javascripts/surveyor/responses.js.coffee
  app/controllers/surveyor/responses_controller.rb
  app/helpers/surveyor/responses_helper.rb
  app/models/sub_service_request.rb
  app/models/survey.rb
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/responses/index.html.haml
  app/views/surveyor/responses/index.js.coffee
  app/views/surveyor/responses/index.json.jbuilder
  spec/controllers/surveyor/responses/get_index_spec.rb
  spec/features/surveyor/responses/user_filters_responses_spec.rb
Labels: MUSC, bug, version 3.3.0

#1403 wth & kg - Add Non-clinical services bug
  app/views/dashboard/study_level_activities/_study_level_activity_form.html.haml
Labels: MUSC, bug, version 3.3.0

#1415 Jl - Service and service provider relation cleanup
  app/models/service.rb
  app/models/service_provider.rb
  spec/factories/service.rb
Labels: MUSC, bug, version 3.3.0

#1417 Short interactions [#158607645]
  app/assets/stylesheets/proper/short_interactions.sass
  app/controllers/short_interactions_controller.rb
  app/models/short_interaction.rb
  app/views/service_requests/right_navigation/_right_navigation.html.haml
  app/views/service_requests/right_navigation/_short_interaction_modal.html.haml
  app/views/short_interactions/create.js.coffee
  app/views/short_interactions/new.js.coffee
  config/defaults.json
  config/locales/proper.en.yml
  config/routes.rb
  db/migrate/20150608144217_create_short_interactions.rb
  db/migrate/20150804173821_add_interaction_type_to_short_interactions.rb
  db/migrate/20160119221809_change_short_interactions_note_field.rb
  db/migrate/20180628185642_add_use_short_interaction_setting.rb
  db/migrate/20180628192745_add_short_interaction_permissible_values.rb
  db/schema.rb
  spec/controllers/short_interactions/get_new_spec.rb
  spec/controllers/short_interactions/post_create_spec.rb
  spec/factories/short_interaction.rb
  spec/features/catalog/provider_adds_short_interaction_spec.rb
  spec/models/short_interaction_spec.rb
  spec/support/permissible_values.rb
Labels: LA CaTS, version 3.3.0

#1420 KG - Save Response Filter Bug
  app/controllers/surveyor/response_filters_controller.rb
Labels: MUSC, bug, version 3.3.0

#1421 KG - Delete Line Item Bug
  app/models/line_item.rb
Labels: MUSC, bug, version 3.3.0

#1423 KG - Translation Parse Errors
  config/locales/en.yml
  config/locales/proper.en.yml
Labels: MUSC, bug, version 3.3.0

#1424 KG - New Form Bug
  app/controllers/surveyor/base_controller.rb
Labels: MUSC, bug, version 3.3.0

#1426 Jl - Status sorting bug
  app/helpers/dashboard/sub_service_requests_helper.rb
  spec/views/dashboard/sub_service_requests/_header.html.haml_spec.rb
Labels: MUSC, bug, version 3.3.0

#1435 Feature spec to add user rights
  db/schema.rb
  spec/features/catalog_manager/organization_forms/user_rights/user_adds_identity_to_table_spec.rb
Labels: MUSC, version 3.3.0

#1436 KG - Admin Edit Export to Excel Bug
  app/views/service_requests/request_report.xlsx.axlsx
Labels: MUSC, bug, version 3.3.0

#1438 KG - Yes/No Question Missing Options
  app/models/question.rb
  spec/factories/question.rb
  spec/models/question/question_spec.rb
Labels: MUSC, bug, version 3.3.0

#1440 SRY - Feature Specs for Fulfillment Rights
  app/assets/javascripts/catalog_manager/form.js.coffee
  spec/features/catalog_manager/organization_forms/fulfillment_rights/user_adds_identity_to_table_spec.rb
  spec/features/catalog_manager/organization_forms/fulfillment_rights/user_manages_clinical_providers_spec.rb
  spec/features/catalog_manager/organization_forms/fulfillment_rights/user_removes_identity_from_table_spec.rb
Labels: MUSC, version 3.3.0

#1441 KG - Pricing Setups Controller Specs
  app/controllers/catalog_manager/pricing_setups_controller.rb
  spec/controllers/catalog_manager/pricing_setups_controller_spec.rb
Labels: MUSC, version 3.3.0

#1447 KG - Delete Catalog Controller Spec
  spec/controllers/catalog_manager/catalog_controller_spec.rb
Labels: MUSC, specs, version 3.3.0

#1443 KG - Pricing Maps Controller Specs
  app/controllers/catalog_manager/pricing_maps_controller.rb
  spec/controllers/catalog_manager/pricing_maps_controller_spec.rb
Labels: MUSC, specs, version 3.3.0

#1418 SPARTReport- Short interaction canned report [#158608322]
  app/models/identity.rb
  app/reports/short_interactions.rb
  app/views/reports/index.html.haml
Labels: LA CaTS, version 3.3.0

#1444 SJ Org general info specs
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  config/routes.rb
  spec/factories/tag.rb
  spec/features/catalog_manager/organization_forms/general_information/user_edits_general_info_spec.rb
Labels: MUSC, specs, version 3.3.0

#1445 KG - Survey Access Code Random Failures
  spec/factories/survey.rb
Labels: MUSC, refactors, version 3.3.0

#1446 KG - Subsidy Maps Controller Specs
  app/controllers/catalog_manager/subsidy_maps_controller.rb
  spec/controllers/catalog_manager/subsidy_maps_controller_spec.rb
  spec/factories/excluded_funding_source.rb
Labels: MUSC, specs, version 3.3.0
