Repository sparc-request/sparc-request, pull requests merged in 2018-08, with the labels that each got.

#1453 KG - Fix Consolidated Request Export
  app/models/protocol.rb
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.3.0

#1455 KG - Export Consolidated Request Division Bug
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.3.0

#1450 KG - Services Controller Specs
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/services_controller.rb
  app/views/catalog_manager/services/_related_services_form.html.haml
  app/views/catalog_manager/services/_service_components_form.html.haml
  app/views/catalog_manager/services/add_related_service.js.coffee
  app/views/catalog_manager/services/remove_related_service.js.coffee
  app/views/catalog_manager/services/update_related_service.js.coffee
  config/routes.rb
  spec/controllers/catalog_manager/services_controller_spec.rb
Labels: MUSC, specs, version 3.3.0

#1457 SRY - Feature specs for Organization Status Options
  app/assets/javascripts/catalog_manager/form.js.coffee
  spec/features/catalog_manager/organization_forms/status_options/user_manages_available_statuses_spec.rb
  spec/features/catalog_manager/organization_forms/status_options/user_manages_default_statuses_toggle_spec.rb
  spec/features/catalog_manager/organization_forms/status_options/user_manages_editable_statuses_spec.rb
Labels: MUSC, specs, version 3.3.0

#1456 KG - Service Level Components Specs
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/services_controller.rb
  config/routes.rb
  spec/features/catalog_manager/service_forms/components/user_adds_new_component_spec.rb
  spec/features/catalog_manager/service_forms/components/user_removes_component_spec.rb
Labels: MUSC, specs, version 3.3.0

#1464 KG - Fix Export Consolidated Request Arm Totals
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.3.0

#1465 KG - Service Program/Core Not Updating
  app/controllers/catalog_manager/services_controller.rb
Labels: MUSC, bug, version 3.3.0

#1466 KG - Update Core List When Chaning Service's Program
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/services_controller.rb
  app/views/catalog_manager/services/_core_dropdown.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
  app/views/catalog_manager/services/reload_core_dropdown.js.coffee
  config/routes.rb
Labels: MUSC, bug, version 3.3.0

#1471 KG - Export Consolidated Request
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, enhancement, version 3.3.0

#1473 SJ - Adding specs for auto adjust modal, and small fixes.
  app/views/catalog_manager/organizations/_increase_decrease_modal.html.haml
  app/views/catalog_manager/services/update_epic_info.js.coffee
  config/locales/catalog_manager.en.yml
  spec/features/catalog_manager/organization_forms/pricing/user_uses_increase_decrease_modal_spec.rb
Labels: MUSC, bug, specs, version 3.3.0

#1472 SRY - Feature Specs for Service General Info
  spec/features/catalog_manager/service_forms/components/user_adds_new_component_spec.rb
  spec/features/catalog_manager/service_forms/general_information/user_edits_general_info_spec.rb
Labels: MUSC, specs, version 3.3.0

#1475 Feature Specs for Service Epic Interface
  spec/features/catalog_manager/service_forms/epic/user_edits_epic_interface_spec.rb
Labels: MUSC, specs, version 3.3.0

#1480 WTH - Admin rate
  app/assets/javascripts/service_calendar.js.coffee
  app/views/service_calendars/master_calendar/otf/_otf_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
  spec/features/dashboard/admin_edit/admin_edits_service_calendar_fields_spec.rb
Labels: MUSC, enhancement, version 3.3.0

#1479 ml - Past Status Data Cleanup
  lib/tasks/clean_up_past_status_data.rake
Labels: version 3.3.0

#1481 KG - Service Form Program/Core Select Updates
  app/models/organization.rb
  app/views/catalog_manager/services/_core_dropdown.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC, enhancement, version 3.3.0

#1482 KG - Select Survey/Form Filter Bug
  app/models/survey.rb
  app/views/surveyor/responses/_filter_responses_form.html.haml
Labels: MUSC, bug, version 3.3.0

#1484 SJ - Reworking logic, adding some handy methods, adding/reworking specs
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/models/identity.rb
  spec/views/dashboard/sub_service_requests/_header.html.haml_spec.rb
Labels: MUSC, bug, enhancement, version 3.3.0

#1485 SJ - Admin rate styling tweaks, tooltip changes
  app/helpers/dashboard/study_level_activities_helper.rb
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
Labels: MUSC, enhancement, version 3.3.0

#1487 Jl - form survey validation
  app/views/surveyor/surveys/form/_survey_fields.html.haml
  app/views/surveyor/surveys/form/_survey_question.html.haml
  spec/features/surveyor/surveys/user_edits_survey_fields_spec.rb
Labels: MUSC, version 3.3.0

#1488 SJ - Admin rate small fixes
  app/helpers/dashboard/study_level_activities_helper.rb
  app/views/service_calendars/master_calendar/otf/_otf_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
  config/locales/dashboard.en.yml
Labels: MUSC, bug, enhancement, version 3.3.0

#1489 display only the nav links to the base modules when logged out [#159804614]
  app/helpers/application_helper.rb
Labels: LA CaTS, bug, version 3.3.0

#1494 SJ - UI float bug
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  app/views/catalog_manager/pricing_maps/create.js.coffee
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC, bug, version 3.3.0

#1499 Jl - form survey validation
  app/helpers/surveyor/surveys_helper.rb
  app/views/surveyor/surveys/form/_survey_question.html.haml
  spec/features/surveyor/surveys/user_activates_survey_spec.rb
Labels: MUSC, version 3.3.0

#1496 KG - Organizations Controller Specs
  spec/controllers/catalog_manager/organizations_controller_spec.rb
Labels: MUSC, specs, version 3.3.0

#1497 KG - Incomplete Form Filter Bug
  app/controllers/surveyor/responses_controller.rb
Labels: MUSC, bug, version 3.3.0

#1501 Fixing consolidated tab, this also fixes the view in the normal calen…
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_line_items.html.haml
Labels: version 3.3.0

#1495 SJ - Status creation defaults
  app/models/organization.rb
  spec/controllers/search/get_services_spec.rb
  spec/controllers/service_requests/get_obtain_research_pricing_spec.rb
  spec/factories/organization.rb
  spec/features/catalog_manager/organization_forms/status_options/user_manages_available_statuses_spec.rb
  spec/features/dashboard/service_requests/user_views_ssrs_spec.rb
  spec/features/service_calendar/user_checks_unchecks_column_spec.rb
  spec/features/service_calendar/user_checks_unchecks_row_spec.rb
  spec/features/service_calendar/user_views_locked_ssr_spec.rb
  spec/models/organization_spec.rb
  spec/models/service_request/update_status_spec.rb
  spec/models/sub_service_request/sub_service_request_spec.rb
  spec/support/fixtures.rb
  spec/support/permissible_values.rb
Labels: MUSC, bug, version 3.3.0

#1500 Ml new service specs
  spec/features/catalog_manager/service_forms/new_service/user_creates_new_service_spec.rb
Labels: specs, version 3.3.0

#1502 KG - Response Filter Include Incomplete Bug
  app/controllers/surveyor/responses_controller.rb
Labels: MUSC, bug, version 3.3.0

#1504 Jl - editable your cost field
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_line_items.html.haml
Labels: MUSC, bug, version 3.3.0

#1506 KG - Response Filter Incomplete Forms
  app/controllers/surveyor/responses_controller.rb
Labels: MUSC, bug, version 3.3.0

#1505 SJ - Access rights fix
  app/controllers/catalog_manager/app_controller.rb
  spec/controllers/catalog_manager/catalog_managers_controller_spec.rb
  spec/controllers/catalog_manager/clinical_providers_controller_spec.rb
  spec/controllers/catalog_manager/organizations_controller_spec.rb
  spec/controllers/catalog_manager/pricing_maps_controller_spec.rb
  spec/controllers/catalog_manager/pricing_setups_controller_spec.rb
  spec/controllers/catalog_manager/service_providers_controller_spec.rb
  spec/controllers/catalog_manager/services_controller_spec.rb
  spec/controllers/catalog_manager/submission_emails_controller_spec.rb
  spec/controllers/catalog_manager/subsidy_maps_controller_spec.rb
  spec/controllers/catalog_manager/super_users_controller_spec.rb
Labels: MUSC, bug, version 3.3.0

#1507 KG - Incomplete Form Response State Filtering
  app/controllers/surveyor/responses_controller.rb
Labels: MUSC, bug, version 3.3.0

#1508 KG - Export Consolidated Request Money Formatting Bug
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, bug, version 3.3.0

#1513 SJ - Fixing issues with ajax toggles re-initializing and breaking
  app/views/catalog_manager/organizations/_status_options_box.html.haml
  app/views/catalog_manager/organizations/toggle_default_statuses.js.coffee
  app/views/catalog_manager/pricing_maps/edit.js.coffee
  app/views/catalog_manager/pricing_maps/new.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.3.0

#1518 KG - Random Survey Spec Failures
  spec/factories/form.rb
  spec/factories/system_survey.rb
  spec/features/surveyor/surveys/user_takes_survey_spec.rb
Labels: MUSC, specs, version 3.4.0

#1520 KG - Update Bootstrap Spec Helpers For Random Failures
  spec/support/features/bootstrap_helpers.rb
Labels: MUSC, specs, version 3.4.0

#1519 KG - Resend Surveys Button Missing
  app/models/sub_service_request.rb
Labels: MUSC, bug, cherry-pick, version 3.3.0

#1325 KG - Tableau Dashboard Embed
  app/lib/data_type_validator.rb
  app/views/catalogs/_catalog_center.html.haml
  app/views/catalogs/_tableau.html.haml
  config/defaults.json
  db/migrate/20180515151912_add_tableau_embed_settings.rb
Labels: MUSC, enhancement, version 3.4.0

#1397 KG - Optimize Service Catalog Queries
  app/controllers/service_requests_controller.rb
  app/models/organization.rb
  app/models/service.rb
  app/views/catalogs/_description.html.haml
  app/views/catalogs/accordion/_cores.html.haml
  app/views/catalogs/accordion/_institutions.html.haml
  app/views/catalogs/accordion/_programs.html.haml
  app/views/catalogs/accordion/_providers.html.haml
  app/views/catalogs/accordion/_services.html.haml
  config/database.yml.example
  spec/lib/dashboard/identity_organizations_spec.rb
Labels: MUSC, refactors, version 3.4.0

#1408 KG - Settings Updates Part 1
  .travis.yml
  app/lib/default_settings_populator.rb
  app/lib/settings_populator.rb
  config/epic.yml.example
  config/initializers/epic_interface.rb
  config/ldap.yml.example
  config/settings/application.json
  config/settings/epic.json
  config/settings/ldap.json
  config/settings/rmid.json
  db/migrate/20170621181959_populate_default_settings_data.rb
  db/migrate/20180205171942_add_funding_configurations_to_settings.rb
  db/migrate/20180326183336_auto_run_ldap_and_epic_import_rakes.rb
  db/migrate/20180705174827_fix_epic_and_ldap_settings.rb
  lib/epic_interface.rb
  lib/tasks/bootstrap.rake
  lib/tasks/import_ldap_yml.rake
  lib/tasks/import_settings.rake
  lib/tasks/regenerate_settings_from_local.rake
  spec/extensions/epic_interface_spec.rb
  spec/support/settings.rb
Labels: MUSC, refactors, version 3.4.0

#1521 SJ - Upgrading grape gem, and making needed changes
  Gemfile
  Gemfile.lock
  app/api/v1/base.rb
  app/api/v1/validators_v1.rb
Labels: MUSC, cherry-pick, security

#1527 KG - Hide Incomplete Response Date
  app/views/surveyor/responses/index.json.jbuilder
Labels: MUSC, enhancement, version 3.3.0
