Repository sparc-request/sparc-request, pull requests merged in 2018-04, with the labels that each got.

#1281 wth - (SPARCRequest & SPARC Dashboard) Document upload bug
  app/models/document.rb
  spec/features/dashboard/protocols/show/documents/user_views_documents_spec.rb
Labels: MUSC, cherry-pick, version 3.2.0

#1291 KG - Survey/Form Migration Bug
  db/migrate/20171023191651_migrate_questionnaire_data_to_surveys.rb
Labels: MUSC, bug, cherry-pick, version 3.2.0

#1292 KG - Survey/Form Migration Section Naming Issue
  db/migrate/20171023191651_migrate_questionnaire_data_to_surveys.rb
Labels: MUSC, bug, cherry-pick, version 3.2.0

#1294 wth - (SPARCDashboard) Epic Queue Past Tab "Type" Bug
  app/views/dashboard/epic_queues/_epic_queue_list.html.haml
  config/locales/dashboard.en.yml
  lib/tasks/send_to_epic.rake
Labels: MUSC, cherry-pick, version 3.2.0

#1295 SJ - Fix for admin access rights [#156556008]
  app/models/protocol.rb
Labels: MUSC, bug, cherry-pick

#1279 small label fix [#153600730]
  config/locales/proper.en.yml
Labels: MUSC, cherry-pick, version 3.2.0

#1284 Jl - service batch auditing bug
  app/models/organization.rb
Labels: MUSC, bug, version 3.3.0

#1286 Jl - epic user email bug
  app/models/protocol.rb
Labels: MUSC, bug, version 3.3.0

#1287 wth - (SPARCRequest) Update 3rd party libraries
  Gemfile.lock
Labels: MUSC, version 3.3.0

#1290 JM - (SPARCDashboard) Coverage Analysis Only Show Hospital Services
  app/controllers/service_requests_controller.rb
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/models/arm.rb
  app/views/service_requests/coverage_analysis.xlsx.axlsx
Labels: MUSC, version 3.3.0

#1293 JM - (SPARCForm) View Improvements: Add Submitted By, Add Link, Wrapping
  app/assets/stylesheets/surveyor/responses.sass
  app/views/surveyor/responses/_table.html.haml
  app/views/surveyor/responses/index.json.jbuilder
  config/locales/surveyor.en.yml
Labels: MUSC, version 3.3.0

#1298 JM- (SPARCRequest) Step 2: Add Styling to Finished SSRs
  app/helpers/service_requests_helper.rb
  app/views/service_requests/protocol/_service.html.haml
  app/views/service_requests/protocol/_service_list.html.haml
Labels: MUSC, version 3.3.0

#1300 SJ - Fixing disabled status issue [#156813143]
  app/views/catalog_manager/shared/_available_statuses.html.haml
  db/migrate/20180416170741_correct_available_statuses.rb
  db/schema.rb
Labels: MUSC, bug, cherry-pick, version 3.2.0

#1305 Jl - Subject count bug
  app/models/arm.rb
Labels: MUSC, bug, cherry-pick, version 3.2.0
