Repository sparc-request/sparc-request, pull requests merged in 2018-02, with the labels that each got.

#1241 Jl - finished status select refactor
  app/helpers/dashboard/sub_service_requests_helper.rb
Labels: MUSC, version 3.2.0

#1243 Jl - adding in audit comments to service update script
  lib/tasks/update_hb_services.rake
Labels: MUSC, version 3.2.0

#1244 wth - (SPARCRequest Step 3 & SPARCDashboard) Adding 2 new Timeline Fi…
  app/assets/javascripts/dashboard/milestone.js.coffee
  app/controllers/dashboard/milestones_controller.rb
  app/controllers/service_requests_controller.rb
  app/views/dashboard/milestones/update.js.coffee
  app/views/dashboard/protocols/_milestone.html.haml
  app/views/service_requests/service_details/_details_dates.html.haml
  db/migrate/20180126140905_add_initial_amount_and_negotiated_amount_to_protocols.rb
  db/schema.rb
  spec/api/v1/protocols/get_protocol_spec.rb
  spec/api/v1/protocols/get_protocols_spec.rb
  spec/api/v1/protocols/get_protocols_with_ids_spec.rb
Labels: MUSC, version 3.2.0

#1248 Jl - Bad audit data bug
  app/models/sub_service_request.rb
Labels: MUSC, bug, cherry-pick

#1246 wth - (SPARCRequest) Upgrade to 5.1.5
  Gemfile
  Gemfile.lock
Labels: MUSC, version 3.2.0

#1237 Chanage partial to renamed file FIXES #1236
  app/views/layouts/dashboard/application.html.haml
Labels: bug

#1249 JM- Remove or update SR in first_draft status
  lib/tasks/remove_or_update_SR_in_first_draft_status.rake
Labels: MUSC, version 3.2.0

#1247 Configurable Funding Module [#154785195]
  app/assets/javascripts/funding/documents.js.coffee
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/funding.sass
  app/controllers/application_controller.rb
  app/controllers/funding/services_controller.rb
  app/helpers/application_helper.rb
  app/helpers/funding/documents_helper.rb
  app/helpers/funding/services_helper.rb
  app/models/identity.rb
  app/models/service.rb
  app/views/funding/services/_documents.html.haml
  app/views/funding/services/_title.html.haml
  app/views/funding/services/documents.json.jbuilder
  app/views/funding/services/index.html.haml
  app/views/funding/services/index.json.jbuilder
  app/views/funding/services/show.html.haml
  app/views/layouts/funding.html.haml
  config/defaults.json
  config/initializers/assets.rb
  config/locales/funding.en.yml
  config/routes.rb
  db/migrate/20180205171942_add_funding_configurations_to_settings.rb
  lib/tasks/initialize_funding_related_premissible_values.rake
  spec/controllers/funding/services/get_documents_spec.rb
  spec/controllers/funding/services/get_index_spec.rb
  spec/controllers/funding/services/get_show_spec.rb
Labels: LA CaTS, version 3.2.0

#1251 wth - Use Yarn to manage our front-end assets
  config/initializers/assets.rb
  package.json
Labels: MUSC, version 3.2.0

#1260 KG - Form Builder Migration Bug
  db/migrate/20171023144302_add_new_columns_to_surveys_and_responses.rb
Labels: MUSC, bug, version 3.2.0

#1257 Jtm optional information label change
  app/views/dashboard/protocols/form/_study_fields.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_financial_information.html.haml
  app/views/protocols/form/_study_fields.html.haml
  app/views/protocols/form/study_form_sections/_financial_information.html.haml
  app/views/protocols/view_details/_financial_information.html.haml
  app/views/protocols/view_details/_study_fields.html.haml
  config/locales/en.yml
  spec/views/proper/protocols/view_details.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.2.0

#1258 Removed inactive services from related services search [#152038451]
  app/controllers/catalog_manager/services_controller.rb
Labels: MUSC, enhancement, version 3.2.0

#1256 Jtm add service rate to nc service table
  app/assets/javascripts/dashboard/study_level_activities.js.coffee
  app/controllers/dashboard/line_items_controller.rb
  app/helpers/dashboard/study_level_activities_helper.rb
  app/views/dashboard/line_items/_study_level_activity.json.jbuilder
  app/views/dashboard/line_items/update.js.coffee
  app/views/dashboard/study_level_activities/_study_level_activities_table.html.haml
  config/locales/dashboard.en.yml
  spec/controllers/dashboard/line_items/put_update_spec.rb
Labels: MUSC, enhancement, version 3.2.0

#1262 Jtm consolidated request changes
  app/views/dashboard/protocols/show.xlsx.axlsx
Labels: MUSC, enhancement, version 3.2.0
