Repository sparc-request/sparc-request, pull requests merged in 2019-03, with the labels that each got.

#1733 Move up Step 2 error message location
  app/views/service_requests/protocol.html.haml
  app/views/service_requests/protocol/_protocol_display.html.haml
Labels: LA CaTS, version 3.5.0

#1734 KG - Batch Delete Users + Related Email Logic Improvement
  app/assets/javascripts/application.js
  app/assets/javascripts/associated_users.js.coffee
  app/assets/javascripts/batch-select.js
  app/assets/javascripts/dashboard/application.js
  app/assets/javascripts/dashboard/associated_users.js.coffee
  app/assets/stylesheets/bootstrap-custom.sass
  app/controllers/associated_users_controller.rb
  app/controllers/dashboard/associated_users_controller.rb
  app/helpers/associated_users_helper.rb
  app/helpers/dashboard/associated_users_helper.rb
  app/lib/associated_user_creator.rb
  app/mailers/notifier.rb
  app/mailers/user_mailer.rb
  app/models/project_role.rb
  app/models/protocol.rb
  app/views/notifier/notify_primary_pi_for_epic_user_removal.html.haml
  app/views/user_mailer/_user_info_table.html.haml
  config/locales/en.yml
  spec/controllers/associated_users/delete_destroy_spec.rb
  spec/controllers/dashboard/associated_users/delete_destroy_spec.rb
  spec/features/dashboard/protocols/show/authorized_users/delete_authorized_user_spec.rb
  spec/features/dashboard/protocols/show/authorized_users/edit_authorized_user_spec.rb
  spec/features/proper/protocol/user_deletes_authorized_user_spec.rb
  spec/lib/associated_user_creator_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/protocol/email_about_change_in_authorized_user_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1735 KG - Login Routing Improvements
  app/assets/javascripts/catalog.js.coffee
  app/controllers/identities/omniauth_callbacks_controller.rb
  app/controllers/identities/registrations_controller.rb
  app/controllers/identities/sessions_controller.rb
  app/views/service_requests/catalog.html.haml
  config/routes.rb
Labels: MUSC, enhancement, version 3.5.0

#1742 SJ - Fixing flash message issues with components
  app/views/catalog_manager/services/change_components.js.coffee
Labels: MUSC, bug, version 3.5.0

#1743 KG - Remove Linked Quantity / Total
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/services_controller.rb
  app/controllers/dashboard/line_items_controller.rb
  app/models/line_item.rb
  app/models/service_request.rb
  app/views/catalog_manager/services/_related_services_form.html.haml
  app/views/catalog_manager/services/_related_services_row.html.haml
  app/views/catalog_manager/services/update_related_service.js.coffee
  config/locales/catalog_manager.en.yml
  db/migrate/20190301212606_remove_linked_qty_fields.rb
  db/schema.rb
  lib/tasks/update_related_services.rake
  spec/features/catalog_manager/service_forms/related_services/user_edits_service_relation_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1744 SRY - SPARCRequest confirmation page changes
  app/helpers/service_requests_helper.rb
  app/views/service_requests/confirmation.html.haml
  app/views/service_requests/navigation/_steps.html.haml
  app/views/service_requests/obtain_research_pricing.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1746 Kg - Add Service Bug Step 2
  app/views/catalogs/accordion/_services.html.haml
Labels: MUSC, bug, version 3.5.0

#1748 KG - Internet Explorer Alignment
  app/assets/stylesheets/proper/service_catalog.sass
Labels: MUSC, bug, version 3.5.0

#1762 SJ - Update bootstrap sass
  Gemfile
  Gemfile.lock
Labels: MUSC, dependencies

#1756 ML - SJ - Navbar and breadcrumb consistency pt2
  app/assets/stylesheets/dashboard/layout.sass
  app/views/dashboard/sub_service_requests/show.html.haml
  app/views/layouts/dashboard/_dashboard_header.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1760 KG - Service Catalog Carets / Other Panel Issues
  app/assets/stylesheets/bootstrap-custom.sass
  app/assets/stylesheets/flex-utils.sass
  app/views/catalogs/accordion/_institutions.html.haml
  app/views/catalogs/accordion/_providers.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_affiliations.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_financial_information.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_impact_areas.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_study_information.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_study_type.html.haml
  app/views/protocols/form/_project_roles_fields.html.haml
  app/views/protocols/form/study_form_sections/_affiliations.html.haml
  app/views/protocols/form/study_form_sections/_financial_information.html.haml
  app/views/protocols/form/study_form_sections/_impact_areas.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_study_information.html.haml
  app/views/protocols/form/study_form_sections/_study_type.html.haml
Labels: MUSC, bug, version 3.5.0

#1761 ML - make dashboard filters persist
  app/controllers/dashboard/protocols_controller.rb
Labels: MUSC, enhancement, version 3.5.0

#1766 KG - Fulfillment Synchronization Report Script V1
  app/models/arm.rb
  app/models/line_item.rb
  app/models/line_items_visit.rb
  app/models/protocol.rb
  app/models/shard/fulfillment/arm.rb
  app/models/shard/fulfillment/base.rb
  app/models/shard/fulfillment/fulfillment.rb
  app/models/shard/fulfillment/line_item.rb
  app/models/shard/fulfillment/procedure.rb
  app/models/shard/fulfillment/protocol.rb
  app/models/shard/fulfillment/visit.rb
  app/models/shard/fulfillment/visit_group.rb
  app/models/visit.rb
  app/models/visit_group.rb
  config/fulfillment_db.yml
  config/initializers/shard.rb
  lib/tasks/fulfillment_synchronization_report.rake
Labels: MUSC, enhancement, version 3.5.0

#1780 Fix Dashboard filter protocols bug
  app/models/organization.rb
Labels: LA CaTS, bug, version 3.5.0

#1785 KG - Fix Single Service Landing Page
  app/views/catalogs/_catalog_center.html.haml
  app/views/catalogs/accordion/_services.html.haml
  app/views/service_requests/catalog.html.haml
  spec/features/proper/catalog/user_views_single_service_spec.rb
Labels: MUSC, bug, version 3.5.0

#1792 SJ - Fixes for sync
  .gitignore
  .travis.yml
  config/deploy.rb
  config/fulfillment_db.yml.example
Labels: MUSC, bug, enhancement, version 3.5.0

#1774 Jl - clincard split notify
  lib/tasks/process_ssrs_move.rake
Labels: MUSC, version 3.5.0
