Repository sparc-request/sparc-request, pull requests merged in 2019-11, with the labels that each got.

#2057 Jl - Protocol Merge Bug
  app/controllers/dashboard/protocol_merges_controller.rb
Labels: MUSC, bug, version 3.6.0

#2050 SJ - Fixing Bootstrap Specs
  app/assets/javascripts/application.js
  spec/features/dashboard/authorized_users/user_deletes_authorized_user_spec.rb
  spec/features/proper/protocol/authorized_users/user_deletes_authorized_user_spec.rb
Labels: MUSC, bootstrap-4

#2058 Jl - Protocol Merge Bug
  app/controllers/dashboard/protocol_merges_controller.rb
Labels: MUSC, bug, version 3.6.0

#2063 small notifications table display changes
  app/views/dashboard/notifications/_table.html.haml
  config/locales/dashboard.en.yml
Labels: LA CaTS, bootstrap-4, version 3.6.0

#2064 SJ - Fixing service search when not logged in
  app/controllers/application_controller.rb
Labels: MUSC, bug, version 3.6.0

#2065 KG - Locked/Completed SSRs Rework
  app/assets/javascripts/service_calendar.js.coffee
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/assets/stylesheets/service_calendar.scss
  app/controllers/application_controller.rb
  app/controllers/dashboard/clinical_line_items_controller.rb
  app/controllers/line_items_visits_controller.rb
  app/controllers/notes_controller.rb
  app/controllers/search_controller.rb
  app/controllers/service_calendars_controller.rb
  app/helpers/dashboard/study_level_activities_helper.rb
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/helpers/notes_helper.rb
  app/helpers/service_calendar_helper.rb
  app/helpers/service_requests_helper.rb
  app/lib/cost_analysis/service_request.rb
  app/views/dashboard/sub_service_requests/_header.html.haml
  app/views/dashboard/sub_service_requests/_study_level_activities.html.haml
  app/views/dashboard/sub_service_requests/details/_timeline.html.haml
  app/views/line_items/update.js.coffee
  app/views/line_items_visits/update.js.coffee
  app/views/notes/_index.html.haml
  app/views/notes/create.js.coffee
  app/views/notes/destroy.js.coffee
  app/views/notes/index.js.coffee
  app/views/notes/update.js.coffee
  app/views/protocols/form/_study_type_questions.html.haml
  app/views/protocols/show.html.erb
  app/views/service_calendars/_quantity.html.haml
  app/views/service_calendars/_subject_count.html.haml
  app/views/service_calendars/_units_per_quantity.html.haml
  app/views/service_calendars/master_calendar/otf/_otf_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/_check_visit_columns.html.haml
  app/views/service_calendars/master_calendar/pppv/_pppv_calendar.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_visit_input.html.haml
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_visit_input.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_column.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_row.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_visit_input.html.haml
  app/views/service_calendars/toggle_calendar_column.js.coffee
  app/views/service_calendars/toggle_calendar_row.js.coffee
  app/views/service_requests/cart/_cart_sub_service_requests.html.haml
  app/views/visits/update.js.coffee
  config/locales/dashboard.en.yml
  config/routes.rb
Labels: MUSC, enhancement, version 3.6.0

#2068 SJ - Ontology changes
  app/controllers/catalog_manager/organizations_controller.rb
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  config/locales/catalog_manager.en.yml
  db/migrate/20191119144844_add_secondary_ontology_tag_to_organizations.rb
  db/schema.rb
  spec/features/catalog_manager/organization_forms/general_information/user_edits_general_info_spec.rb
  spec/support/permissible_values.rb
Labels: MUSC, Side Branch Project, enhancement

#2069 SAW - Bootstrap 4 Survey and Form bugs
  app/assets/javascripts/global.js.coffee
  app/helpers/surveyor/responses_helper.rb
  app/lib/data_type_validator.rb
  app/models/question_response.rb
  app/views/surveyor/responses/create.js.coffee
  app/views/surveyor/responses/form/_response_question.html.haml
  app/views/surveyor/responses/form/form_partials/_checkbox_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_country_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_date_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_dropdown_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_email_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_likert_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_multiple_dropdown_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_number_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_phone_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_radio_button_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_state_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_text_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_textarea_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_time_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_yes_no_form_partial.html.haml
  app/views/surveyor/responses/form/form_partials/_zipcode_form_partial.html.haml
  app/views/surveyor/responses/update.js.coffee
  app/views/surveyor/survey_updater/update.js.coffee
  app/views/surveyor/surveys/form/form_partials/_checkbox_example.html.haml
  app/views/surveyor/surveys/form/form_partials/_dropdown_example.html.haml
  app/views/surveyor/surveys/form/form_partials/_radio_button_example.html.haml
  spec/lib/data_type_validator_spec.rb
  spec/models/question_response/question_response_spec.rb
Labels: bootstrap-4

#2070 Adjust link buttons in funding Actions column
  app/helpers/funding/documents_helper.rb
Labels: version 3.6.0

#2072 fix incorrect id selector
  app/assets/javascripts/dashboard/notifications.js.coffee
Labels: LA CaTS, bug, version 3.6.0
