Repository sparc-request/sparc-request, pull requests merged in 2019-04, with the labels that each got.

#1772 KG - Add Dropdown Search Functionality
  app/models/survey.rb
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/responses/_surveys_dropdown.html.haml
  spec/features/surveyor/responses/user_filters_responses_spec.rb
  spec/features/surveyor/responses/user_saves_filter_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1784 KG - Shareable Service Link
  app/assets/javascripts/global.js.coffee
  app/views/catalog_manager/services/_general_info_form.html.haml
  config/locales/catalog_manager.en.yml
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.5.0

#1799 KG - Admin Edit Remove Service (Line Item) Bug
  app/assets/javascripts/dashboard/study_schedule_management.js.coffee
  app/controllers/dashboard/multiple_line_items_controller.rb
  app/models/line_item.rb
  app/views/dashboard/multiple_line_items/_remove_line_items_form.html.haml
  app/views/dashboard/multiple_line_items/destroy_line_items.js.coffee
  app/views/dashboard/multiple_line_items/edit_line_items.js.coffee
Labels: MUSC, bug, version 3.5.0

#1800 KG - Single Service Landing Page Redirect if Service Inactive
  app/controllers/service_requests_controller.rb
  spec/controllers/service_requests/get_catalog_spec.rb
Labels: MUSC, bug, version 3.5.0

#1801 KG - Admin Edit Visit Group Insert into Position Bug
  app/helpers/visit_groups_helper.rb
Labels: MUSC, bug, version 3.5.0

#1819 KG - Catalog Service Order Bug
  app/views/catalogs/_description.html.haml
  app/views/catalogs/accordion/_cores.html.haml
  app/views/catalogs/accordion/_services.html.haml
  app/views/service_requests/protocol/_service_list.html.haml
Labels: MUSC, bug, version 3.5.0

#1765 SRY - Fixing survey latest sent date errors
  app/models/sub_service_request.rb
  app/views/dashboard/sub_service_requests/_request_details.html.haml
  config/locales/dashboard.en.yml
Labels: MUSC, enhancement, version 3.5.0

#1773 ML - notification email format update
  app/controllers/dashboard/messages_controller.rb
  app/controllers/dashboard/notifications_controller.rb
  app/mailers/user_mailer.rb
  app/views/user_mailer/notification_received.html.haml
  config/locales/en.yml
Labels: MUSC, not ready, version 3.5.0

#1820 KG - Hide Shareable Service Link if Inactive
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1821 SJ - Email root url setting
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/testing.rb
Labels: MUSC, enhancement, version 3.5.0

#1822 SJ - Adding method for direct link, and adding to api
  app/api/v1/entities/full.rb
  app/models/service.rb
  app/views/catalog_manager/services/_general_info_form.html.haml
  spec/api/v1/services/get_service_spec.rb
  spec/api/v1/services/get_services_spec.rb
  spec/api/v1/services/get_services_with_ids_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1823 KG - Authorized User Email Improvements
  app/views/user_mailer/_intro.html.haml
  app/views/user_mailer/_user_info_table.html.haml
  config/locales/en.yml
  spec/mailers/user_mailer_spec.rb
  spec/support/user_mailer_emails/tables.rb
Labels: MUSC, enhancement, version 3.5.0

#1826 KG - Fix Survey Distribution
  app/models/organization.rb
  app/models/service.rb
Labels: MUSC, bug, version 3.5.0

#1827 SJ - Adding rescue for config changes
  config/environments/development.rb
  config/environments/production.rb
  config/environments/staging.rb
  config/environments/testing.rb
Labels: MUSC, bug, version 3.5.0

#1829 KG - Coverage Analysis Report CPT Code
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/models/arm.rb
  app/views/service_requests/coverage_analysis.xlsx.axlsx
Labels: MUSC, bug, version 3.5.0

#1832 SJ - Adding in patient registrar controls
  app/views/catalog_manager/organizations/_fulfillment_rights_form.html.haml
  app/views/catalog_manager/organizations/_fulfillment_rights_row.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1828 KG - Fix Service Request Navigation
  app/controllers/application_controller.rb
  app/controllers/service_requests_controller.rb
  app/views/layouts/_header.html.haml
  app/views/service_requests/add_service.js.coffee
Labels: MUSC, bug, version 3.5.0

#1831 Fix add/remove ssrs bug when protocol has not yet created
  app/models/service_request.rb
Labels: LA CaTS, bug, version 3.5.0

#1836 KG - Add Pending Status
  app/models/permissible_value.rb
  db/seeds/permissible_values/2.0.5/statuses.csv
Labels: MUSC, enhancement, version 3.5.0

#1835 KG - Make Fulfillment Sharding Optional
  config/initializers/shard.rb
Labels: MUSC, bug, version 3.5.0
