Repository sparc-request/sparc-request, pull requests merged in 2019-02, with the labels that each got.

#1676 KG - Protocols Report Investigational Devices
  app/lib/reports/protocols.rb
Labels: MUSC, enhancement, version 3.5.0

#1697 KG - Fix Service Catalog Description HTML Escape
  app/controllers/search_controller.rb
  app/views/catalogs/_description.html.haml
  app/views/catalogs/accordion/_cores.html.haml
  app/views/catalogs/accordion/_services.html.haml
Labels: MUSC, bug, version 3.5.0

#1698 KG - Service Catalog Service Styling Bugs / IE Overflow
  app/assets/stylesheets/proper/service_catalog.sass
Labels: MUSC, bug, version 3.5.0

#1695 ML - update contact info to settings table
  app/views/error_pages/internal_server_error.html.haml
  app/views/error_pages/not_found.html.haml
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.5.0

#1708 Sparc request branding - Replacing 'SPARC Request' with 'SPARCRequest'
  INSTALL.md
  app/lib/initial_cm_creation.rb
  app/views/feedback/_form.html.haml
  app/views/nokogiri.xml
  app/views/notifier/notify_for_epic_access_removal.html.haml
  app/views/notifier/notify_for_epic_rights_changes.html.haml
  app/views/notifier/notify_for_epic_user_approval.html.haml
  app/views/notifier/notify_primary_pi_for_epic_user_final_review.html.haml
  app/views/notifier/notify_primary_pi_for_epic_user_removal.html.haml
  config/locales/catalog_manager.en.yml
  config/locales/en.yml
  config/locales/proper.en.yml
Labels: LA CaTS, version 3.5.0

#1709 KG - Disable Admin Edit Status Dropdown if Never Submitted
  app/views/dashboard/sub_service_requests/_header.html.haml
  config/locales/dashboard.en.yml
  spec/features/dashboard/sub_service_requests/user_is_saved_on_past_status_spec.rb
  spec/views/dashboard/sub_service_requests/_header.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1711 KG - Coverage Analysis Report Epic CPT Code
  app/models/arm.rb
Labels: MUSC, enhancement, version 3.5.0

#1713 KG - Fix Protocols Reporting Investigational Devices
  app/lib/reports/protocols.rb
Labels: MUSC, bug, version 3.5.0

#1714 KG - Related Service Search Display Bug and Optimization
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/controllers/catalog_manager/app_controller.rb
  app/controllers/search_controller.rb
  spec/features/catalog_manager/service_forms/related_services/user_adds_related_service_spec.rb
Labels: MUSC, bug, version 3.5.0

#1715 ML - add info table to satisfaction survey email
  app/mailers/survey_notification.rb
  app/views/survey_notification/_info_table.html.haml
  app/views/survey_notification/service_survey.html.haml
  config/locales/surveyor.en.yml
  spec/mailers/survey_notification_spec.rb
  spec/models/sub_service_request/distribute_surveys_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1716 KG - Improve Service Calendar Visit Input Usability
  app/assets/javascripts/service_calendar.js.coffee
  app/assets/stylesheets/service_calendar.sass
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1718 ML - remove about sparcrequest button
  app/assets/stylesheets/proper/service_catalog.sass
  app/views/catalogs/_about_section.html.haml
  app/views/service_requests/catalog.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1719 Attempt to fix the affiliate netid issue
  app/models/identity.rb
Labels: MUSC, version 3.5.0

#1721 Jl - ui for protocol merge
  app/assets/javascripts/dashboard/protocol_merges.js.coffee
  app/controllers/dashboard/protocol_merges_controller.rb
  app/lib/dashboard/fix_ssr_ids.rb
  app/lib/dashboard/merge_srs.rb
  app/views/dashboard/protocol_merges/_merge_tool.html.haml
  app/views/dashboard/protocol_merges/perform_protocol_merge.js.coffee
  app/views/dashboard/protocol_merges/show.html.haml
  app/views/layouts/dashboard/_dashboard_header.html.haml
  config/routes.rb
  spec/views/layouts/dashboard/_dashboard_header.html.haml_spec.rb
Labels: MUSC, version 3.5.0

#1723 ML - add request_owner info to survey email
  app/views/survey_notification/_info_table.html.haml
  config/locales/surveyor.en.yml
  spec/mailers/survey_notification_spec.rb
  spec/models/sub_service_request/distribute_surveys_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1720 Adding delayed job monitoring [#163951193]
  Gemfile
  Gemfile.lock
  app/lib/directory.rb
  app/models/identity.rb
  config/defaults.json
  config/schedule.rb
  db/migrate/20190213152838_add_dj_slackwebhook_url.rb
  lib/tasks/delayed_job_monitor.rake
  spec/support/ldap.rb
Labels: MUSC, version 3.5.0

#1725 ML - navbar and breadcrumb consistency
  app/assets/stylesheets/dashboard/layout.sass
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/reports_controller.rb
  app/views/layouts/dashboard/_dashboard_header.html.haml
Labels: MUSC, enhancement, version 3.5.0

#1729 KG - Step 2 Collapse & Flex Utilities
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/bootstrap-custom.sass
  app/assets/stylesheets/catalog_manager/application.scss
  app/assets/stylesheets/dashboard/application.scss
  app/assets/stylesheets/dashboard/service_requests.scss
  app/assets/stylesheets/flex-utils.sass
  app/assets/stylesheets/service_calendar.sass
  app/views/associated_users/_table.html.haml
  app/views/catalog_manager/catalog/_accordion.html.haml
  app/views/catalog_manager/catalog/_program_accordion.html.haml
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  app/views/catalog_manager/organizations/_increase_decrease_modal.html.haml
  app/views/catalog_manager/organizations/_pricing_setup.html.haml
  app/views/catalog_manager/pricing_maps/_pricing_map_form.html.haml
  app/views/catalog_manager/pricing_setups/_pricing_setup_form.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
  app/views/catalog_manager/services/_new.html.haml
  app/views/catalog_manager/services/_pricing_map.html.haml
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/dashboard/protocols/_protocols_list.html.haml
  app/views/dashboard/protocols/_summary.html.haml
  app/views/dashboard/service_requests/_service_requests.html.haml
  app/views/dashboard/sub_service_requests/_header.html.haml
  app/views/funding/services/show.html.haml
  app/views/protocols/_summary.html.haml
  app/views/service_calendars/master_calendar/otf/_otf_calendar.html.haml
  app/views/service_calendars/master_calendar/pppv/_pppv_calendar.html.haml
  app/views/service_calendars/master_calendar/pppv/_pppv_freeze_header_button.html.haml
  app/views/subsidies/_approved_subsidy.html.haml
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/responses/edit.html.haml
  app/views/surveyor/responses/new.html.haml
  app/views/surveyor/surveys/form/_survey_section.html.haml
  app/views/surveyor/surveys/preview.html.haml
  spec/features/surveyor/responses/user_saves_filter_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1730 ML - add padding below steps
  app/assets/stylesheets/layout.sass
Labels: MUSC, enhancement, version 3.5.0

#1696 SJ - SRY - Modify past statuses
  app/models/sub_service_request.rb
  db/migrate/20190116192754_add_new_status_to_past_statuses.rb
  db/migrate/20190118194740_remove_old_status_from_past_statuses.rb
  lib/tasks/fix_past_status_data.rake
Labels: MUSC, enhancement, version 3.5.0

#1712 KG - Original Submitted Date Backfill Script
  lib/tasks/backfill_original_submission_dates.rake
Labels: MUSC, enhancement, version 3.5.0
