Repository sparc-request/sparc-request, pull requests merged in 2019-01, with the labels that each got.

#1673 KG - Import eIRB Task Updates
  lib/tasks/import_historical_eirb_fields.rake
Labels: MUSC, bug, version 3.4.0

#1684 SJ - Fixing navbar whitelist issue
  app/helpers/application_helper.rb
Labels: MUSC, cherry-pick, version 3.4.0

#1685 KG - Coverage Analysis Report use_epic Bug
  app/views/service_requests/coverage_analysis.xlsx.axlsx
Labels: MUSC, bug, cherry-pick, version 3.4.0

#1690 SJ - Fixes for CSP
  .env.example
  config/environments/production.rb
  config/initializers/content_security_policy.rb
Labels: MUSC, bug, cherry-pick, version 3.4.0

#1670 KG - Hide No Description Available (Service Catalog, Catalog Manager)
  app/assets/javascripts/catalog.js.coffee
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/controllers/search_controller.rb
  app/helpers/service_requests_helper.rb
  app/views/catalogs/_description.html.haml
  app/views/catalogs/accordion/_cores.html.haml
  app/views/catalogs/accordion/_services.html.haml
  config/locales/proper.en.yml
Labels: MUSC, enhancement, version 3.5.0

#1671 KG - Pricing Setup Labels
  app/assets/stylesheets/layout.sass
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/models/available_status.rb
  app/models/permissible_value.rb
  app/views/associated_users/_user_form.html.haml
  app/views/catalog_manager/pricing_maps/_pricing_map_form.html.haml
  app/views/catalog_manager/pricing_setups/_pricing_setup_form.html.haml
  app/views/catalog_manager/subsidy_maps/_form.html.haml
  app/views/dashboard/documents/_document_form.html.haml
  app/views/dashboard/protocols/form/_project_fields.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/dashboard/protocols/form/study_form_sections/_study_information.html.haml
  app/views/documents/_document_form.html.haml
  app/views/protocols/form/_project_fields.html.haml
  app/views/protocols/form/study_form_sections/_research_involving.html.haml
  app/views/protocols/form/study_form_sections/_study_information.html.haml
  config/locales/catalog_manager.en.yml
  db/schema.rb
Labels: MUSC, enhancement, version 3.5.0

#1672 KG - Catalog Manager Surveys Label
  config/locales/catalog_manager.en.yml
  spec/features/catalog_manager/organization_forms/associated_surveys/user_adds_associated_survey_to_table_spec.rb
  spec/features/catalog_manager/organization_forms/associated_surveys/user_removes_associated_survey_spec.rb
Labels: MUSC, enhancement, version 3.5.0

#1674 SJ - Line Item error bug
  app/models/service_request.rb
Labels: MUSC, bug, version 3.5.0

#1677 KG - Catalog Search Text Add EAP ID
  config/locales/catalog_manager.en.yml
  config/locales/proper.en.yml
Labels: MUSC, enhancement, version 3.5.0

#1678 KG - Note Color Bugs
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/dashboard/application.scss
  app/assets/stylesheets/dashboard/epic_queues.sass
  app/assets/stylesheets/notes.sass
  app/assets/stylesheets/service_calendar.sass
  app/helpers/dashboard/study_level_activities_helper.rb
  app/helpers/notes_helper.rb
Labels: MUSC, bug, version 3.5.0

#1693 SJ - Cherry Pick changes
  app/assets/javascripts/dashboard/application.js
  config/initializers/content_security_policy.rb
Labels: bug, cherry-pick, version 3.4.0
