Repository sparc-request/sparc-request, pull requests merged in 2019-05, with the labels that each got.

#1838 KG - Fix Login "NoMethodError"
  app/controllers/application_controller.rb
  app/controllers/identities/omniauth_callbacks_controller.rb
Labels: MUSC, bug, version 3.5.0

#1839 KG - Pending Status Bug / Add "Incomplete" to CSV for Import
  app/models/available_status.rb
  db/seeds/permissible_values/2.0.5/statuses.csv
Labels: MUSC, bug, version 3.5.0

#1840 KG - Fix Document Management "Back" button
  app/controllers/service_requests_controller.rb
  spec/controllers/service_requests/get_document_management_spec.rb
Labels: MUSC, bug, version 3.5.0

#1841 Jl - Merge button styling error
  app/views/layouts/dashboard/_dashboard_header.html.haml
Labels: MUSC, bug, version 3.5.0

#1842 SJ - Modals can't be closed by off-click
  app/assets/javascripts/admin/admin.identities.js
  app/assets/javascripts/global.js.coffee
Labels: MUSC, enhancement, version 3.5.0

#1844 KG - SSR Submission Status Bugs
  app/models/sub_service_request.rb
  spec/models/sub_service_request/update_status_and_notify_spec.rb
Labels: MUSC, bug, version 3.5.0

#1845 KG - Fix Original Submitted Date Script
  lib/tasks/backfill_original_submission_dates.rake
Labels: MUSC, bug, version 3.5.0

#1846 SJ - Changes to subsidy text
  app/controllers/dashboard/subsidies_controller.rb
  config/locales/en.yml
Labels: MUSC, bug, version 3.5.0

#1847 KG - Service Request Revamp Bugs
  app/helpers/service_requests_helper.rb
  app/lib/notifier_logic.rb
  app/models/service_request.rb
  app/views/service_requests/navigation/_footer.html.haml
Labels: MUSC, bug, version 3.5.0

#1848 set callback once method is complete
  app/lib/dashboard/merge_srs.rb
Labels: MUSC, bug, version 3.5.0

#1851 JM - (SPARCRequest) Submission Confirmation Notes Bug
  app/assets/javascripts/confirmation.js.coffee
  app/views/notes/_index.html.haml
  app/views/notes/_table.html.haml
  app/views/notes/index.js.coffee
Labels: version 3.5.0

#1853 JM - (SPARCRequest) Submission Confirmation Notes Bug
  app/assets/images/institution_logo2017.png
  app/assets/images/org_logo2017.png
  app/helpers/notes_helper.rb
  app/views/notes/_form.html.haml
Labels: version 3.5.0

#1854 SJ - Disabling confirmation page table
  app/views/service_requests/confirmation.html.haml
  spec/features/proper/confirmation/user_views_ssr_spec.rb
Labels: MUSC, bug

#1855 KG - Coverage Analysis "Show Chosen Services" Logic Bugs
  app/models/arm.rb
  app/views/service_requests/coverage_analysis.xlsx.axlsx
Labels: MUSC, bug, cherry-pick, version 3.5.0

#1857 SRY - Fixing Archive Protocol Email Title
  app/mailers/protocol_mailer.rb
Labels: MUSC, bug, cherry-pick, version 3.5.0

#1858 Kg - Fix Admin Export SSR Report
  app/controllers/service_requests_controller.rb
  app/views/service_requests/request_report.xlsx.axlsx
Labels: MUSC, bug, cherry-pick, version 3.5.0

#1859 KG - Send to Fulfillment Multi-click Bug
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.5.0

#1856 KG - SPARCForms Survey Dropdown Bug
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/bootstrap-select-custom.js
  app/assets/javascripts/bootstrap-select.js
  app/assets/javascripts/catalog_manager/application.js
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/assets/javascripts/dashboard/application.js
  app/assets/javascripts/dashboard/notifications.js.coffee
  app/assets/javascripts/dashboard/protocols.js.coffee
  app/assets/javascripts/surveyor/surveys.js.coffee
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/bootstrap-select-custom.scss
  app/assets/stylesheets/bootstrap-select.css
  app/assets/stylesheets/catalog_manager/application.scss
  app/assets/stylesheets/dashboard/application.scss
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/views/dashboard/notifications/_dropdown.html.haml
  app/views/surveyor/responses/_surveys_dropdown.html.haml
  app/views/surveyor/surveys/_actions_dropdown.html.haml
  spec/features/catalog_manager/organization_forms/pricing/user_edits_pricing_setup_funding_source_rates_spec.rb
  spec/features/dashboard/protocols/index/filters/admin_user_filters_my_admin_protocols_with_search_spec.rb
  spec/features/dashboard/protocols/index/filters/admin_user_filters_my_protocols_with_search_spec.rb
  spec/features/dashboard/protocols/index/filters/general_user_filters_with_search_spec.rb
  spec/features/proper/service_calendar/user_interacts_with_consolidated_request_tab.rb
  spec/features/proper/service_calendar/user_interacts_with_quantity_billing_tab_spec.rb
  spec/features/proper/service_calendar/user_interacts_with_template_tab_spec.rb
  spec/features/surveyor/responses/user_filters_responses_spec.rb
  spec/features/surveyor/surveys/user_edits_survey_fields_spec.rb
  spec/features/surveyor/surveys/user_previews_survey_spec.rb
  spec/features/surveyor/surveys/user_takes_survey_spec.rb
  spec/support/features/bootstrap_helpers.rb
  spec/support/features/wait_helpers.rb
  spec/support/pages/dashboard/protocols/index_page.rb
  vendor/assets/javascripts/bootstrap-select.js
  vendor/assets/stylesheets/bootstrap-select.css
  vendor/assets/stylesheets/bootstrap-select.css.map
Labels: MUSC, bug, cherry-pick, version 3.5.0

#1860 SJ - Fixing log-out bug
  app/controllers/application_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.5.0

#1861 KG - Fulfillment Synchronization Report Final Updates
  app/models/application_record.rb
  app/models/shard/fulfillment/base.rb
  app/models/shard/fulfillment/fulfillment.rb
  app/models/shard/fulfillment/line_item.rb
  app/models/shard/fulfillment/procedure.rb
  app/models/shard/fulfillment/protocol.rb
  app/models/shard/fulfillment/visit.rb
  app/models/sub_service_request.rb
  lib/tasks/fulfillment_synchronization_report.rake
  spec/models/document_spec.rb
Labels: MUSC, bug, enhancement, version 3.5.0
