Repository sparc-request/sparc-request, pull requests merged in 2019-12, with the labels that each got.

#2079 Hide Surveys column in Admin Edit if the ssr doesn't have any available surveys
  app/models/sub_service_request.rb
  app/views/dashboard/sub_service_requests/_header.html.haml
Labels: LA CaTS, bug, version 3.6.0

#2092 SAW - Guarantor Fields Bug
  app/views/protocols/form/_financial_information.html.haml
  app/views/protocols/form/_protocol_information.html.haml
  config/locales/en.yml
Labels: bootstrap-4, version 3.6.0

#2104 SAW - New Request Popup Window Bug
  app/assets/javascripts/service_requests.js.coffee
  app/views/catalogs/accordion/_services.html.haml
Labels: bootstrap-4, version 3.6.0

#2105 SAW - Guarantor Fields Bug
  app/views/protocols/form/_financial_information.html.haml
Labels: bootstrap-4, version 3.6.0

#2118 SAW - Guarantor Fields Bug
  app/views/protocols/view_details/_financial_information.html.haml
  app/views/protocols/view_details/_protocol_information.html.haml
Labels: bootstrap-4, version 3.6.0

#2123 SJ - Fix for recognize path issues
  .travis.yml
  app/controllers/application_controller.rb
  app/controllers/dashboard/subsidies_controller.rb
  app/controllers/service_requests_controller.rb
  app/controllers/surveyor/responses_controller.rb
  app/helpers/application_helper.rb
  app/views/dashboard/protocols/update.js.coffee
  app/views/dashboard/sub_service_requests/_view_modal.html.haml
  app/views/protocols/_milestones.html.haml
  app/views/service_requests/protocol/_protocol_information.html.haml
  app/views/service_requests/service_details.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2124 KG - Document Table Height Too Many Providers
  app/controllers/documents_controller.rb
  app/helpers/documents_helper.rb
  app/models/document.rb
  app/views/dashboard/documents/index.json.jbuilder
  app/views/documents/index.json.jbuilder
  config/locales/en.yml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2127 SAW - Service Revision Buttons Display Bug
  app/assets/javascripts/service_calendar.js.coffee
  app/views/service_calendars/_header.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2128 KG - Open Core Collapse When Viewing Single Service From Link
  app/views/catalogs/accordion/_cores.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2129 KG - Add Blank Option to Owner Dropdown
  app/views/dashboard/sub_service_requests/_header.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2130 SJ - Add/remove service bug
  app/controllers/dashboard/clinical_line_items_controller.rb
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/helpers/arms_helper.rb
  app/helpers/dashboard/clinical_line_items_helper.rb
  app/views/arms/_form.html.haml
  app/views/dashboard/clinical_line_items/_form.html.haml
  app/views/dashboard/clinical_line_items/edit.js.coffee
  app/views/dashboard/clinical_line_items/new.js.coffee
  app/views/service_calendars/_header.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2131 SJ - Making some text changes
  config/locales/en.yml
Labels: MUSC, cherry-pick, enhancement, version 3.6.0

#2134 KG - Admin Edit Tables Not Rendering On Page Load
  app/views/dashboard/sub_service_requests/refresh_tab.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2126 KG - Admin Edit Duplicate PPPV Service Silent Error
  app/controllers/dashboard/clinical_line_items_controller.rb
  app/models/line_item.rb
  spec/api/v1/line_items/get_line_items_spec.rb
  spec/api/v1/line_items/get_line_items_with_ids_spec.rb
  spec/lib/notifier_logic/update_ssrs_and_send_emails_spec.rb
  spec/models/line_item_spec.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2135 SAW - Never Submitted Confirmation Bug
  app/controllers/service_requests_controller.rb
  app/lib/remove_service.rb
  app/views/service_requests/remove_service.js.coffee
  spec/features/proper/catalog/user_removes_service_spec.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2125 KG - Fix View SSR / Export SSR Services
  app/controllers/service_requests_controller.rb
  app/lib/dashboard/service_calendars.rb
  spec/lib/dashboard/service_calendars_spec.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2140 KG - Admin Edit Duplicate Service Error Message Text Change
  config/locales/en.yml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2142 KG - Improve Calendar Check/Uncheck Row/Column
  app/controllers/service_calendars_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2141 SAW - Never Submitted Confirmation Bug Fixes
  app/lib/remove_service.rb
  app/models/sub_service_request.rb
  app/views/service_requests/remove_service.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2143 KG - SPARC Cloud Send Identity Sign Up to Shards
  app/controllers/application_controller.rb
Labels: MUSC, Side Branch Project, bug

#2144 Jl - Service calendar width adjustment
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_header.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_max_total_per_patient.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_total_cost_per_study.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2145 SJ - Linked services bug fix
  app/models/line_item.rb
  app/models/service_request.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0
