Repository sparc-request/sparc-request, pull requests merged in 2019-09, with the labels that each got.

#2005 fixing small typo
  app/controllers/dashboard/associated_users_controller.rb
  app/views/associated_users/edit.js.coffee
  app/views/dashboard/associated_users/edit.js.coffee
Labels: LA CaTS, bootstrap-4, bug

#1885 Check if SPARCFulfillment only when fulfillment_contingent_on_catalog_manager is turned on
  app/controllers/dashboard/protocol_merges_controller.rb
Labels: LA CaTS, bug, version 3.6.0

#1904 Archive protocol email bug
  app/controllers/dashboard/protocols_controller.rb
  app/mailers/protocol_mailer.rb
  config/locales/en.yml
Labels: LA CaTS, bug, version 3.6.0

#1984 Jl - hb service update
  lib/tasks/update_hb_services.rake
Labels: MUSC, version 3.6.0

#1986 Jl - Adding authorized users email bug
  app/views/user_mailer/_user_info_table.html.haml
  spec/mailers/user_mailer_spec.rb
  spec/support/user_mailer_emails/tables.rb
Labels: MUSC, bug, version 3.6.0

#2004 Fix NoMethodError error on edit profile - nil professional organization
  app/controllers/identities/registrations_controller.rb
Labels: LA CaTS, bootstrap-4, bug

#1988 Professional organization disappearing dropdowns bug
  app/views/associated_users/update_professional_organizations.js.coffee
Labels: LA CaTS, bootstrap-4, bug

#1989 Professional organizations reset bug
  app/assets/javascripts/associated_users_form.js.coffee
Labels: LA CaTS, bootstrap-4, bug

#2028 SJ - Adding billing manager
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/views/catalog_manager/organizations/_user_rights_row.html.haml
  config/locales/catalog_manager.en.yml
  db/migrate/20190918150314_add_billing_manager_to_super_users.rb
  db/schema.rb
Labels: MUSC, enhancement, version 3.6.0
