Repository sparc-request/sparc-request, pull requests merged in 2019-10, with the labels that each got.

#1972 Bbootstrap 4 - SPARCFunding
  app/assets/javascripts/application.js
  app/assets/javascripts/funding/documents.js.coffee
  app/assets/stylesheets/funding.sass
  app/controllers/funding/services_controller.rb
  app/helpers/funding/documents_helper.rb
  app/views/funding/services/_documents.html.haml
  app/views/funding/services/_title.html.haml
  app/views/funding/services/index.html.haml
  app/views/funding/services/show.html.haml
  app/views/layouts/funding/application.html.haml
  config/locales/funding.en.yml
Labels: LA CaTS, bootstrap-4, version 3.6.0

#2010 Jl - Nexus pricing refactor
  lib/tasks/import_pricing_maps.rake
Labels: MUSC, refactors, version 3.6.0

#2032 KG - Add News Feed API Token For Atlassian API
  app/lib/news_feed/api_adapter.rb
  app/lib/news_feed/atlassian_adapter.rb
  app/lib/news_feed/base.rb
  config/defaults.json
Labels: MUSC, bug, version 3.6.0

#2036 KG - Persist Protocol & Response Filters
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/surveyor/responses_controller.rb
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/dashboard/protocols/index.js.coffee
  app/views/surveyor/responses/index.js.coffee
Labels: MUSC, enhancement, version 3.6.0

#2021 Jl - User rights search bug
  app/assets/javascripts/catalog_manager/catalog.js.coffee
Labels: MUSC, bug, version 3.6.0

#2016 Jl - service creation bug
  app/models/organization.rb
  app/views/catalog_manager/services/_core_dropdown.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC, bug, version 3.6.0
