Repository sparc-request/sparc-request, pull requests merged in 2020-08, with the labels that each got.

#2434 Jl - Select all t quantities
  app/assets/stylesheets/service_calendar.scss
  app/controllers/visits_controller.rb
  app/views/visits/_form.html.haml
  app/views/visits/update.js.coffee
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.8.0

#2442 Fix modify requests access bug
  app/controllers/concerns/associated_users_controller_shared.rb
Labels: LA CaTS, bug, version 3.8.0

#2443 KG - Escape quotes when pulling titles from RMID
  app/views/protocols/validate_rmid.js.coffee
Labels: MUSC, bug, version 3.8.0

#2444 KG - Visits Dropdown Overflow Bug
  app/assets/javascripts/custom/bootstrap-select-custom.es6
  app/lib/dashboard/service_calendars.rb
  package.json
  yarn.lock
Labels: MUSC, bug, version 3.8.0

#2445 KG - Step 2 Don't redirect if removing own authorized user and you're an overlord
  app/controllers/concerns/associated_users_controller_shared.rb
Labels: MUSC, bug, version 3.8.0

#2451 notify remote around update only if fulfillment_contingent_on_catalog…
  app/models/protocol.rb
  app/models/service.rb
  app/models/sub_service_request.rb
Labels: LA CaTS, bug, version 3.8.0

#2450 KG - Documents "Share with all providers" checkbox
  app/assets/javascripts/documents.js.coffee
  app/controllers/concerns/documents_controller_shared.rb
  app/helpers/documents_helper.rb
  app/models/document.rb
  app/views/documents/_form.html.haml
  config/locales/en.yml
  db/migrate/20200805132132_add_share_all_to_documents.rb
  db/schema.rb
  spec/factories/document.rb
  spec/features/dashboard/documents/user_adds_document_spec.rb
  spec/features/proper/document_management/user_adds_document_spec.rb
  spec/models/document_spec.rb
Labels: MUSC, enhancement, version 3.8.0

#2448 KG - Site Footer Updates, Supported Browsers
  app/assets/javascripts/service_calendar.js.coffee
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/layout.scss
  app/assets/stylesheets/service_calendar.scss
  app/views/layouts/_footer.html.haml
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.8.0

#2455 KG - Fix YAML in Site Footer
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/layout.scss
  app/views/layouts/_footer.html.haml
Labels: MUSC, bug, version 3.8.0

#2467 Jl - All T Quantity Check All Bug
  app/views/service_calendars/master_calendar/pppv/template/_select_column.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_row.html.haml
Labels: MUSC, bug, version 3.8.0

#2454 KG - Visit Group Editing Updates
  app/assets/javascripts/custom/bootstrap-custom.es6
  app/assets/javascripts/global.js.coffee
  app/assets/javascripts/service_calendar.js.coffee
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/assets/stylesheets/service_calendar.scss
  app/helpers/visit_groups_helper.rb
  app/lib/dashboard/service_calendars.rb
  app/views/arms/_form.html.haml
  app/views/service_calendars/_subject_count.html.haml
  app/views/service_calendars/master_calendar/pppv/_visit_group.html.haml
  app/views/service_calendars/master_calendar/pppv/_visit_group_page_select.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_column.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_row.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_visit_input.html.haml
  app/views/service_calendars/table.js.coffee
  app/views/service_calendars/toggle_calendar_column.js.coffee
  app/views/service_calendars/toggle_calendar_row.js.coffee
  app/views/service_requests/service_details.html.haml
  app/views/visit_groups/_form.html.haml
  app/views/visit_groups/edit.js.coffee
  app/views/visit_groups/new.js.coffee
  app/views/visit_groups/update.js.coffee
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.8.0

#2464 Jl - Protocol Update Cwf Api Bug
  app/jobs/remote_service_notifier_job.rb
Labels: MUSC, bug, version 3.8.0

#2469 Jl - Set All Indicated Visits to Default Quantity
  app/controllers/protocols_controller.rb
  app/models/visit.rb
  app/views/protocols/update_billing.js.coffee
Labels: MUSC, enhancement, version 3.8.0

#2470 Change Export Report label to 'Budget Template'
  config/locales/dashboard.en.yml
Labels: LA CaTS, enhancement, version 3.8.0

#2471 (SPARCReport) Add User's Email Column to Survey Responses Report
  app/lib/reports/survey_responses.rb
Labels: LA CaTS, enhancement, version 3.8.0

#2472 Add few columns to Unique PI report
  app/lib/reports/unique_pi.rb
Labels: LA CaTS, enhancement, version 3.8.0

#2473 Add Division column to SPARC Account report
  app/lib/reports/sparc_account.rb
Labels: LA CaTS, enhancement, version 3.8.0

#2477 KG - IE Site Footer Bug
  app/assets/stylesheets/footer.scss
  app/assets/stylesheets/layout.scss
Labels: MUSC, bug, version 3.8.0

#2476 Capitalize the ORCID column header in Unique PI report
  app/lib/reports/unique_pi.rb
Labels: LA CaTS, version 3.8.0
