Repository sparc-request/sparc-request, pull requests merged in 2020-09, with the labels that each got.

#2478 SAW - OnCore Minimum Footprint Push
  app/lib/oncore_protocol.rb
Labels: MUSC, version 3.8.0

#2480 SAW - Added logger to OnCore REST API
  app/lib/oncore_protocol.rb
Labels: MUSC, version 3.8.0

#2482 KG - Prevent Form Multi-Submission During Modal Hide Animation
  app/assets/javascripts/custom/bootstrap-custom.es6
Labels: MUSC, bug, version 3.8.0

#2483 SJ - RMID Validation Changes
  lib/tasks/update_protocol_with_validated_rm.rake
Labels: MUSC, enhancement, version 3.8.0

#2485 SAW - OnCore REST API changes
  app/lib/oncore_protocol.rb
  app/models/professional_organization.rb
  spec/features/dashboard/protocols/show/user_pushes_protocol_to_oncore_spec.rb
  spec/lib/oncore_protocol_spec.rb
  spec/support/webmock.rb
Labels: MUSC, version 3.8.0

#2486 SJ - Epic Error
  app/controllers/dashboard/protocols_controller.rb
Labels: MUSC, enhancement, version 3.8.0

#2489 Jl - Retain Indicated Quantity When Setting Default Billing
  app/controllers/protocols_controller.rb
Labels: MUSC, enhancement, version 3.8.0

#2492 SAW - OnCore minimum footprint push
  app/controllers/dashboard/protocols_controller.rb
  app/lib/oncore_protocol.rb
  app/views/dashboard/protocols/push_to_oncore.js.coffee
  config/defaults.json
  config/locales/en.yml
  spec/lib/oncore_protocol_spec.rb
Labels: MUSC, version 3.8.0

#2493 SJ - Login Changes
  app/views/devise/sessions/_form.html.haml
  app/views/devise/sessions/new.html.haml
Labels: MUSC, bug, enhancement, version 3.8.0

#2502 SJ - Protocol Merge Bug
  app/lib/dashboard/merge_srs.rb
Labels: MUSC, bug, version 3.8.0

#2491 KG - updating visit group editing, changing pages
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/controllers/application_controller.rb
  app/controllers/visit_groups_controller.rb
  app/helpers/service_calendar_helper.rb
  app/helpers/visit_groups_helper.rb
  app/lib/dashboard/service_calendars.rb
  app/models/line_item.rb
  app/models/service_request.rb
  app/views/line_items_visits/update.js.coffee
  app/views/service_calendars/_table.html.haml
  app/views/service_calendars/master_calendar/pppv/_pppv_calendar.html.haml
  app/views/service_calendars/master_calendar/pppv/_visit_group.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_max_total_per_patient.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_pppv_totals.html.haml
  app/views/service_calendars/toggle_calendar_column.js.coffee
  app/views/service_calendars/toggle_calendar_row.js.coffee
  app/views/visit_groups/_form.html.haml
  app/views/visit_groups/edit.js.coffee
  app/views/visit_groups/new.js.coffee
  app/views/visit_groups/update.js.coffee
  app/views/visits/update.js.coffee
  spec/views/service_calendars/master_calendar/pppv/totals/_pppv_totals.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.8.0

#2503 KG - Fix Visit Group Changing Page / Tiny Calendar Style
  app/assets/stylesheets/service_calendar.scss
  app/controllers/service_requests_controller.rb
  app/controllers/visit_groups_controller.rb
  app/lib/dashboard/service_calendars.rb
  app/views/dashboard/sub_service_requests/_view_modal.html.haml
  app/views/service_calendars/_view_full_calendar.html.haml
Labels: MUSC, bug, version 3.8.0

#2507 keep the most recent service request
  app/lib/dashboard/merge_srs.rb
Labels: LA CaTS, bug, version 3.8.0

#2509 SAW - Protocol Report default to any date, include unsubmitted option
  app/lib/reports/protocols.rb
Labels: version 3.8.0

#2510 SRY - Adding multiple IRBs to Protocols report and Service Request report
  app/lib/reports/protocols.rb
  app/lib/reports/service_requests.rb
Labels: MUSC, version 3.8.0

#2511 Jl - Duplicate Protocol Bug
  app/controllers/protocols_controller.rb
  app/views/protocols/create.js.coffee
  app/views/protocols/form/_footer.html.haml
  spec/features/proper/protocol/protocols/user_adds_irb_records_spec.rb
  spec/features/proper/protocol/protocols/user_creates_project_spec.rb
  spec/features/proper/protocol/protocols/user_creates_study_spec.rb
Labels: MUSC, bug, cherry-pick, version 3.8.0

#2512 SAW - Changed Epic Root for component4
  config/defaults.json
  db/migrate/20200925173318_rename_epic_study_root_setting.rb
  lib/epic_interface.rb
  spec/extensions/epic_interface_spec.rb
Labels: MUSC, cherry-pick, version 3.8.0

#2516 Jl - Message Sort Bug
  app/helpers/dashboard/notifications_helper.rb
Labels: MUSC, bug, cherry-pick, version 3.8.0
