Repository sparc-request/sparc-request, pull requests merged in 2020-07, with the labels that each got.

#2415 Fix Admin Edit sla fulfillment related bugs
  app/helpers/dashboard/study_level_activities_helper.rb
Labels: LA CaTS, bug, cherry-pick, version 3.7.0

#2417 Jl - Study question type
  config/constants.yml
  spec/support/fixtures.rb
Labels: MUSC, bug, version 3.8.0

#2418 Update Epic Language in Submission Emails
  app/views/notifier/_welcome.html.haml
  config/locales/en.yml
  spec/mailers/notifier/submitted_spec.rb
  spec/support/emails/notes.rb
Labels: LA CaTS, enhancement, version 3.8.0

#2422 Fix ssr deletion bug
  app/lib/remove_service.rb
Labels: LA CaTS, bug, version 3.8.0

#2433 SJ - Patient Registrar Restrictions
  app/controllers/catalog_manager/app_controller.rb
  app/controllers/catalog_manager/clinical_providers_controller.rb
  app/controllers/catalog_manager/organizations_controller.rb
  app/controllers/catalog_manager/patient_registrars_controller.rb
  app/lib/study_type_finder.rb
  app/views/catalog_manager/organizations/_fulfillment_rights_form.html.haml
  app/views/catalog_manager/organizations/_fulfillment_rights_row.html.haml
Labels: MUSC, enhancement, version 3.8.0

#2437 SJ - Epic User Validation
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/protocols.scss
  app/controllers/dashboard/protocols_controller.rb
  app/models/protocol.rb
  app/views/associated_users/_table.html.haml
  config/locales/dashboard.en.yml
Labels: MUSC, bug, enhancement, version 3.8.0

#2438 Jl - User Edit Bug
  config/routes.rb
Labels: MUSC, bug, version 3.8.0
