Repository sparc-request/sparc-request, pull requests merged in 2020-12, with the labels that each got.

#2559 SRY - Creating Modified Rate report
  app/lib/reports/modified_rate_report.rb
Labels: MUSC, version 3.9.0

#2566 KG - Header Logos Slight HTML Adjustment
  app/views/layouts/_header.html.haml
Labels: MUSC, refactors

#2569 KG - Study Level Activities Tab Style Consistency
  app/views/dashboard/sub_service_requests/_study_level_activities.html.haml
Labels: MUSC, bug, version 3.9.0

#2575 SRY - Disabling service dropdown when fulfillment exists
  app/views/dashboard/study_level_activities/_form.html.haml
  app/views/dashboard/study_level_activities/edit.js.coffee
  config/locales/dashboard.en.yml
Labels: MUSC, version 3.9.0

#2576 SAW - Add Institution and Primary PI to OnCore Protocol
  app/lib/oncore_protocol.rb
  config/defaults.json
  spec/features/dashboard/protocols/show/user_pushes_protocol_to_oncore_spec.rb
  spec/lib/oncore_protocol_spec.rb
  spec/support/webmock.rb
Labels: MUSC, version 3.9.0

#2565 SRY - Fixing inactive indicator in dashboard filter
  app/lib/dashboard/grouped_organizations.rb
Labels: MUSC, version 3.9.0
