Repository sparc-request/sparc-request, pull requests merged in 2020-10, with the labels that each got.

#2523 Jl - Sync Delete Bug
  app/controllers/dashboard/sub_service_requests_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.8.0

#2522 KG - Move Visit Cherrypick
  app/controllers/visit_groups_controller.rb
  app/helpers/visit_groups_helper.rb
  app/models/arm.rb
  app/models/visit_group.rb
  app/views/visit_groups/_form.html.haml
  app/views/visit_groups/update.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.8.0

#2529 KG - More Move Visit Bugs (Logic Updates)
  app/controllers/visit_groups_controller.rb
  app/models/visit_group.rb
Labels: MUSC, bug, cherry-pick, version 3.8.0

#2521 SJ - Text Change
  config/locales/dashboard.en.yml
Labels: MUSC, enhancement, version 3.9.0

#2533 Jl - Document Upload Sort Bug
  app/views/dashboard/documents/index.json.jbuilder
  app/views/documents/index.json.jbuilder
Labels: MUSC, bug, version 3.9.0

#2534 SAW - Epic Queue Date Sorting Bug
  app/helpers/dashboard/epic_queues_helper.rb
  app/models/epic_queue.rb
  app/views/dashboard/epic_queues/index.json.jbuilder
Labels: MUSC, version 3.9.0

#2536 Jl - SLA Add Line Item Bug
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
  app/views/dashboard/study_level_activities/_form.html.haml
Labels: MUSC, bug, version 3.9.0

#2545 KG - Move Visit Bugs
  app/models/visit_group.rb
  app/views/visit_groups/_form.html.haml
Labels: MUSC, bug, cherry-pick, version 3.8.0
