Repository sparc-request/sparc-request, pull requests merged in 2020-11, with the labels that each got.

#2547 KG - Move Visit Bugs again and again and again and again and again and...
  app/models/visit_group.rb
  app/views/visit_groups/_form.html.haml
Labels: MUSC, bug, cherry-pick, version 3.8.0

#2537 SRY - Adding inactive organization indicator to dropdown
  app/views/catalog_manager/services/_core_dropdown.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC

#2548 Fix SPARCRequset and SPARCDashboard Logo Bug
  app/controllers/dashboard/base_controller.rb
  app/views/layouts/_header.html.haml
Labels: LA CaTS, bug, cherry-pick, version 3.8.0, version 3.9.0

#2549 KG - Move Visit Bugs
  app/models/visit_group.rb
Labels: MUSC, bug, cherry-pick, version 3.9.0

#2550 fix date sorting bug in several bootstrap tables
  app/views/dashboard/fulfillments/index.json.jbuilder
  app/views/dashboard/study_level_activities/index.json.jbuilder
  app/views/dashboard/sub_service_requests/approval_history.json.jbuilder
  app/views/dashboard/sub_service_requests/status_history.json.jbuilder
  app/views/dashboard/sub_service_requests/subsidy_history.json.jbuilder
  app/views/funding/services/documents.json.jbuilder
  app/views/funding/services/index.json.jbuilder
  app/views/surveyor/responses/index.json.jbuilder
Labels: LA CaTS, bug, version 3.9.0

#2553 SAW - Epic Special Character filter for []^|
  app/models/arm.rb
  app/models/protocol.rb
  spec/models/arm/validations_spec.rb
  spec/models/protocol/valid_spec.rb
Labels: MUSC, version 3.9.0
