Repository sparc-request/sparc-request, pull requests merged in 2020-06, with the labels that each got.

#2391 SAW - Epic User Slack Webhook Exception Message
  app/models/epic_user.rb
Labels: MUSC, cherry-pick, version 3.7.0

#2390 KG - Fix Protocols Report Submission Date Range
  app/lib/reports/protocols.rb
Labels: MUSC, bug, cherry-pick, version 3.7.0

#2398 SJ - Required Services Bug
  app/models/service_request.rb
Labels: MUSC, bug, cherry-pick, version 3.7.0

#2406 SJ - Remove SR Approvals
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/controllers/service_requests_controller.rb
  app/lib/notifier_logic.rb
  app/mailers/notifier.rb
  app/models/service_request.rb
  app/views/service_requests/approve_changes.html.haml
  config/routes.rb
  db/migrate/20200617134540_remove_service_request_approvals.rb
  db/schema.rb
  lib/tasks/email_test.rake
  spec/lib/notifier_logic/update_ssrs_and_send_emails_spec.rb
  spec/mailers/notifier/request_amendment_spec.rb
  spec/mailers/notifier/submitted_spec.rb
  spec/support/capybara_support.rb
Labels: MUSC, bug, refactors, version 3.8.0

#2408 Bug Fix-perform fulfillment synch check only when SPARCFulfillment is not enabled
  app/controllers/service_requests_controller.rb
Labels: LA CaTS, bug, version 3.7.0
