Repository sparc-request/sparc-request, pull requests merged in 2020-02, with the labels that each got.

#2204 hide extra fields in study general information view when configuratio…
  app/views/protocols/view_details/_protocol_information.html.haml
  spec/views/protocols/view_details/_protocol_information.html.haml_spec.rb
Labels: LA CaTS, bug, cherry-pick, version 3.6.0

#2176 SAW - Auto-refresh bug for Modified Rate, Add/Delete Services
  Gemfile
  app/views/dashboard/clinical_line_items/create.js.coffee
  app/views/dashboard/clinical_line_items/destroy.js.coffee
  app/views/dashboard/study_level_activities/create.js.coffee
  app/views/dashboard/study_level_activities/destroy.js.coffee
  app/views/line_items/update.js.coffee
Labels: MUSC, bug, version 3.7.0

#2205 Jl - Historical protocol merges
  app/controllers/dashboard/protocols_controller.rb
  app/helpers/dashboard/protocols_helper.rb
  app/views/dashboard/protocols/_table.html.haml
  app/views/dashboard/protocols/index.json.jbuilder
  config/locales/en.yml
  spec/features/dashboard/protocols/index/filters/user_clicks_saved_filter_spec.rb
Labels: MUSC, enhancement, version 3.7.0

#2212 SJ - IE upload bug
  app/views/documents/_form.html.haml
  package.json
  yarn.lock
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2217 SJ - IE Document Upload
  app/views/documents/_form.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2215 SR submission Confirmation page 'Go to" button change
  app/views/service_requests/navigation/_footer.html.haml
  config/locales/proper.en.yml
Labels: LA CaTS, version 3.7.0
