Repository sparc-request/sparc-request, pull requests merged in 2020-01, with the labels that each got.

#2148 KG - Revert use_<oauth_provider>_only Routes Changes
  config/routes.rb
Labels: MUSC, bug, version 3.6.0

#2149 KG - Request Details Datepicker Bug
  app/helpers/application_helper.rb
  app/helpers/dashboard/notifications_helper.rb
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/helpers/notes_helper.rb
  app/views/dashboard/documents/index.json.jbuilder
  app/views/dashboard/fulfillments/index.json.jbuilder
  app/views/dashboard/study_level_activities/index.json.jbuilder
  app/views/dashboard/sub_service_requests/approval_history.json.jbuilder
  app/views/dashboard/sub_service_requests/refresh_tab.js.coffee
  app/views/dashboard/sub_service_requests/status_history.json.jbuilder
  app/views/dashboard/sub_service_requests/subsidy_history.json.jbuilder
  app/views/documents/index.json.jbuilder
  app/views/funding/services/documents.json.jbuilder
  app/views/funding/services/index.json.jbuilder
  app/views/surveyor/responses/index.json.jbuilder
  spec/support/emails/tables.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2150 Jl- Admin rate status bug
  app/controllers/line_items_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2151 KG - Epic Queue Refresh Page Number Bug
  app/assets/stylesheets/custom/bootstrap-table-custom.scss
  app/views/dashboard/epic_queue_records/index.json.jbuilder
  app/views/dashboard/epic_queues/destroy.js.coffee
  app/views/dashboard/epic_queues/index.json.jbuilder
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2152 KG - Improve Push to Epic Performance
  lib/epic_interface.rb
Labels: MUSC, refactors, version 3.7.0

#2155 SAW - Federal Grant Information View Mis-alignment
  app/views/protocols/view_details/_federal_grant_information.html.haml
  app/views/protocols/view_details/_financial_information.html.haml
Labels: MUSC, cherry-pick, version 3.6.0

#2157 SAW - Unique PI Report Date Bug
  app/lib/reports/unique_pi.rb
Labels: MUSC, cherry-pick, version 3.6.0

#2158 KG - RMID Fixes
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/protocols_controller.rb
  app/models/protocol.rb
  config/locales/en.yml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#1863 Fix RVM Gemset Configuration
  .gemset
Labels: MUSC, version 3.6.0

#2154 KG - Move Service Catalog Search
  app/assets/stylesheets/service_requests.scss
  app/views/catalogs/_catalog_center.html.haml
  app/views/catalogs/_service_accordion.html.haml
  config/locales/proper.en.yml
Labels: MUSC, enhancement, version 3.7.0

#2153 KG - [Cloud] Update Homepage Service Provider Contacts
  app/helpers/identities_helper.rb
  app/views/catalogs/_description.html.haml
  config/locales/proper.en.yml
Labels: MUSC, Side Branch Project, enhancement, version 3.7.0

#2164 SAW - Protocol Information Form NCT# Validation Silent Failure
  app/models/human_subjects_info.rb
  app/views/dashboard/protocols/create.js.coffee
  app/views/dashboard/protocols/update.js.coffee
  app/views/protocols/create.js.coffee
  app/views/protocols/update.js.coffee
Labels: bug, cherry-pick, version 3.6.0

#2166 KG - Duplicate Controller Code Refactor / Attempting Bug Fix
  app/assets/stylesheets/custom/bootstrap-table-custom.scss
  app/controllers/associated_users_controller.rb
  app/controllers/concerns/associated_users_controller_shared.rb
  app/controllers/concerns/documents_controller_shared.rb
  app/controllers/concerns/protocols_controller_shared.rb
  app/controllers/dashboard/associated_users_controller.rb
  app/controllers/dashboard/base_controller.rb
  app/controllers/dashboard/documents_controller.rb
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/documents_controller.rb
  app/controllers/protocols_controller.rb
  app/lib/document_remover.rb
  app/views/associated_users/destroy.js.coffee
  app/views/dashboard/associated_users/destroy.js.coffee
  spec/controllers/associated_users/delete_destroy_spec.rb
  spec/lib/document_remover_spec.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2168 [Cloud] KG - New User ldap_uid Error / Add Message About .edu Email
  app/controllers/application_controller.rb
  app/models/identity.rb
  app/views/devise/registrations/_form.html.haml
  config/locales/devise.en.yml
Labels: MUSC, Side Branch Project, bug, version 3.7.0

#2175 Fix create/save study bug when epic is off
  app/models/study.rb
Labels: LA CaTS, bug, cherry-pick, version 3.6.0

#2171 JM - (SPARCFulfillment) Ability to Forfeit Charges
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/super_users_controller.rb
  app/views/catalog_manager/organizations/_user_rights_row.html.haml
  config/locales/catalog_manager.en.yml
  db/migrate/20200112190229_add_allow_credit_to_super_users.rb
Labels: MUSC, version 3.7.0

#2178 KG - Fix RMID Search & Study Type Note Authorization
  app/controllers/protocols_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2177 KG - Attempting to Fix Random Spec Failures
  .travis.yml
  app/views/surveyor/questions/destroy.js.coffee
  app/views/surveyor/responses/create.js.coffee
  spec/features/catalog_manager/service_forms/pricing/user_edits_pricing_map_rates_spec.rb
  spec/features/surveyor/surveys/user_edits_survey_fields_spec.rb
  spec/support/features/bootstrap_helpers.rb
Labels: MUSC, specs, version 3.7.0

#2179 KG - Milestone Fields Missing Bug
  app/views/protocols/_milestones.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2165 Fix Cancel Edit Protocol redirect link from Dashboard
  app/views/protocols/form/_footer.html.haml
Labels: LA CaTS, bug, cherry-pick, version 3.6.0

#2170 SAW - Plain text document upload bug
  app/models/document.rb
  config/locales/en.yml
Labels: MUSC, bug, version 3.7.0

#2172 KG - Add CD2H Language to Homepage
  app/views/catalogs/_welcome.html.haml
  config/locales/proper.en.yml
Labels: MUSC, enhancement, version 3.7.0

#2169 SAW - Epic User API Down Error Handling
  app/controllers/concerns/associated_users_controller_shared.rb
  app/models/epic_user.rb
  app/models/project_role.rb
  config/defaults.json
  config/locales/en.yml
  spec/features/dashboard/authorized_users/user_adds_authorized_user_spec.rb
Labels: MUSC, version 3.7.0

#2180 Jl - Primary pi required bug
  app/models/project_role.rb
  app/models/protocol.rb
  app/views/dashboard/protocols/create.js.coffee
  app/views/protocols/create.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2189 KG - Fix Missing Milestone Parameters
  app/controllers/concerns/protocols_controller_shared.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2190 KG - SU/SP Add Document Bug
  app/controllers/dashboard/documents_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2191 KG - IE Document Upload Testing Remotipart Compatibility
  Gemfile
  Gemfile.lock
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2192 KG - IE Document Upload Bug
  app/assets/javascripts/application.js
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2193 KG - Milestones Not Saving Values Bug
  app/assets/javascripts/protocols.js.coffee
  app/controllers/concerns/protocols_controller_shared.rb
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2194 KG - IE Document Upload Bug Remove Remotipart
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/javascripts/catalog_manager/application.js
  app/views/documents/_form.html.haml
Labels: MUSC, bug, cherry-pick, version 3.6.0

#2199 Jl - Primary pi required bug
  app/views/dashboard/protocols/create.js.coffee
  app/views/protocols/create.js.coffee
Labels: MUSC, bug, cherry-pick, version 3.6.0
