Repository sparc-request/sparc-request, pull requests merged in 2020-05, with the labels that each got.

#2324 SJ - Minor Ordering Bug
  app/views/catalogs/accordion/_services.html.haml
Labels: MUSC, bug, version 3.7.0

#2323 KG - Notification Sharing Feature
  app/assets/stylesheets/components.scss
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/assets/stylesheets/custom/bootstrap-table-custom.scss
  app/assets/stylesheets/dashboard/notifications.scss
  app/controllers/dashboard/notifications_controller.rb
  app/lib/reports/notifications_report.rb
  app/lib/reports/protocols.rb
  app/models/identity.rb
  app/models/notification.rb
  app/views/dashboard/messages/_index.html.haml
  app/views/dashboard/notifications/_dropdown.html.haml
  app/views/dashboard/notifications/_new_notification.html.haml
  app/views/dashboard/notifications/_notifications.html.haml
  app/views/dashboard/notifications/_table.html.haml
  app/views/dashboard/notifications/index.html.haml
  app/views/dashboard/notifications/index.json.jbuilder
  app/views/dashboard/sub_service_requests/_history.html.haml
  app/views/dashboard/sub_service_requests/_notifications.html.haml
  app/views/reports/_setup.html.haml
  app/views/reports/form_partials/_date_range_form_partial.html.haml
  app/views/reports/index.html.haml
  config/locales/dashboard.en.yml
  config/locales/en.yml
  config/locales/reporting.en.yml
  db/migrate/20200424141815_add_shared_to_notifications.rb
  db/schema.rb
  spec/controllers/dashboard/notifications/get_index_spec.rb
  spec/models/notification_spec.rb
  spec/views/dashboard/notifications/_notifications.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.7.0

#2328 Hide federal grant information when not funded is selected
  app/assets/javascripts/protocol_form.js.coffee
Labels: LA CaTS, bug, version 3.7.0

#2326 Remove Catalog Managers Access to Form Responses
  app/controllers/surveyor/responses_controller.rb
  app/models/form.rb
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/responses/index.json.jbuilder
Labels: LA CaTS, bug, version 3.7.0

#2329 KG - Update Get a Cost Estimate Removal Migration
  db/migrate/20200402195743_remove_get_a_cost_estimate_default.rb
Labels: MUSC, bug, version 3.7.0

#2330 SAW - Epic Interface Broken Bug
  lib/epic_interface.rb
Labels: MUSC, version 3.7.0

#2333 UI - Otf table
  app/lib/cost_analysis/generator.rb
  app/lib/cost_analysis/generators/pdf.rb
  app/lib/cost_analysis/oft_table.rb
  app/lib/cost_analysis/service_request.rb
  app/views/dashboard/service_requests/_service_requests.html.haml
  app/views/service_calendars/_view_full_calendar.html.haml
Labels: enhancement, version 3.7.0

#2334 (SPARC NavBar) UI Improvement Needed for Narrow Screens
  app/assets/stylesheets/custom/bootstrap-custom.scss
  app/assets/stylesheets/navbar.scss
  app/views/layouts/_navbar.html.haml
  app/views/layouts/_profile.html.haml
Labels: LA CaTS, enhancement, version 3.7.0

#2336 SJ - Fixing query for incomplete responses
  app/controllers/funding/services_controller.rb
  app/controllers/protocols_controller.rb
  app/controllers/surveyor/responses_controller.rb
  app/helpers/funding/documents_helper.rb
  app/lib/reports/protocols.rb
  app/lib/reports/service_requests.rb
  app/mailers/notifier.rb
  app/models/protocol.rb
  app/models/sub_service_request.rb
  app/views/dashboard/protocols/show.xlsx.axlsx
  app/views/survey_notification/_info_table.html.haml
  app/views/surveyor/responses/index.json.jbuilder
  config/environments/development.rb
  db/schema.rb
  lib/tasks/admin_turnaround_times_report.rake
  lib/tasks/billing_only_report.rake
  lib/tasks/jit_report.rake
  lib/tasks/one_time_fee_report.rake
  lib/tasks/protocol_human_subjects_report.rake
  lib/tasks/submitted_ssrs.rake
Labels: MUSC, bug, version 3.7.0

#2335 KG - Only prompt SSR resubmission if there are SSRs to be resubmitted
  app/views/service_requests/navigation/_footer.html.haml
Labels: MUSC, bug, version 3.7.0

#2338 Jl - Push to epic on update
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/protocols_controller.rb
Labels: MUSC, enhancement, version 3.7.0

#2340 KG - Fix Typo in SSR Resubmission Logic
  app/views/service_requests/navigation/_footer.html.haml
Labels: MUSC, bug, version 3.7.0

#2342 SJ - Incomplete Responses Bug
  app/controllers/surveyor/responses_controller.rb
  app/views/surveyor/responses/index.xlsx.axlsx
Labels: MUSC, bug, version 3.7.0

#2349 KG - More Notification Sharing Updates
  app/assets/javascripts/dashboard/notifications.js.coffee
  app/lib/reports/notifications_report.rb
  app/models/notification.rb
  app/views/dashboard/messages/_index.html.haml
  app/views/dashboard/notifications/_new_notification.html.haml
  app/views/dashboard/notifications/_table.html.haml
  app/views/dashboard/notifications/mark_as_read.js.coffee
  app/views/dashboard/notifications/new.js.coffee
  config/locales/dashboard.en.yml
Labels: MUSC, bug, version 3.7.0

#2346 KG - Import/Remove IRB From RMID Search
  app/assets/javascripts/protocol_form.js.coffee
  app/views/irb_records/_form.html.haml
  app/views/irb_records/create.js.coffee
  app/views/protocols/validate_rmid.js.coffee
Labels: MUSC, bug, version 3.7.0

#2345 KG - Update "Get a Cost Estimate" Available/Editable Statuses for Default Status Orgs
  db/migrate/20200402195743_remove_get_a_cost_estimate_default.rb
Labels: MUSC, bug, version 3.7.0

#2341 KG - Fix SSR Resubmission Issues
  app/assets/javascripts/review.js.coffee
  app/lib/notifier_logic.rb
  app/models/service_request.rb
  app/views/service_requests/navigation/_footer.html.haml
  app/views/service_requests/system_satisfaction_survey.js.coffee
  app/views/surveyor/responses/create.js.coffee
  config/environments/development.rb
Labels: MUSC, bug, version 3.7.0

#2343 Short Interaction minute must be a positive integer
  app/models/short_interaction.rb
Labels: LA CaTS, bug, version 3.7.0

#2360 KG - Remove "Get a Cost Estimate" from list of disabled statuses for catalog manager
  app/models/available_status.rb
Labels: MUSC, bug, version 3.7.0

#2361 KG - Add "Primary" text for Primary IRB
  app/views/irb_records/_irb_record.html.haml
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.7.0

#2357 Conditionally Display Sign Up Button
  app/views/layouts/_profile.html.haml
  config/locales/en.yml
Labels: LA CaTS, enhancement

#2362 Jl - Non-clinical line item fulfillment synch
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
  app/controllers/dashboard/study_level_activities_controller.rb
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/controllers/service_requests_controller.rb
  app/helpers/dashboard/study_level_activities_helper.rb
  app/helpers/dashboard/sub_service_requests_helper.rb
  app/helpers/service_calendar_helper.rb
  app/models/fulfillment_synchronization.rb
  app/models/shard/fulfillment/fulfillment.rb
  app/models/shard/fulfillment/line_item.rb
  app/models/sub_service_request.rb
  app/views/dashboard/study_level_activities/update.js.coffee
  config/locales/dashboard.en.yml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20200518155844_add_synch_to_fulfillment_to_sub_service_request.rb
  db/migrate/20200518200713_create_fulfillment_synchs.rb
  db/schema.rb
Labels: MUSC, enhancement, version 3.7.0

#2364 Jl - Spec fixes for fulfillment synch
  app/controllers/service_requests_controller.rb
  spec/api/v1/sub_service_requests/get_sub_service_request_spec.rb
  spec/api/v1/sub_service_requests/get_sub_service_requests_spec.rb
  spec/api/v1/sub_service_requests/get_sub_service_requests_with_ids_spec.rb
Labels: MUSC, version 3.7.0

#2365 KG - Fix typo in epic queue push rake task
  lib/tasks/send_to_epic.rake
Labels: MUSC, bug, version 3.7.0

#2366 Jl - Protocol-only and multiple epic queue record bug
  app/controllers/dashboard/protocols_controller.rb
  app/controllers/protocols_controller.rb
Labels: MUSC, bug, version 3.7.0

#2367 KG - "Get a Cost Estimate" & Updatable Status updates
  app/views/service_requests/_ssr_resubmission_form.html.haml
  db/migrate/20200402195743_remove_get_a_cost_estimate_default.rb
Labels: MUSC, bug, enhancement, version 3.7.0

#2368 change 'Sign In / Sign Up' label to 'Sign In'
  config/locales/en.yml
Labels: LA CaTS, enhancement, version 3.7.0

#2369 Jl - otf fulfillment line item synch bugs
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/helpers/dashboard/study_level_activities_helper.rb
  app/helpers/service_calendar_helper.rb
  app/views/dashboard/sub_service_requests/synch_to_fulfillment.js.coffee
  config/locales/dashboard.en.yml
Labels: MUSC, bug, version 3.7.0

#2370 KG - Fix RMID API IRB Synchronization & Synchronization Errors When RMID Server Down
  app/models/protocol.rb
  app/views/irb_records/_irb_record.html.haml
  app/views/irb_records/create.js.coffee
  app/views/irb_records/update.js.coffee
  app/views/protocols/form/research_involving/_human_subjects.html.haml
  app/views/protocols/validate_rmid.js.coffee
  spec/features/dashboard/protocols/new/user_adds_irb_records_spec.rb
  spec/features/dashboard/protocols/new/user_creates_project_spec.rb
  spec/features/dashboard/protocols/new/user_creates_study_spec.rb
  spec/features/proper/protocol/protocols/user_creates_project_spec.rb
  spec/features/proper/protocol/protocols/user_creates_study_spec.rb
  spec/views/irb_records/_irb_record.html.haml_spec.rb
Labels: MUSC, bug, version 3.7.0

#2371 SAW - SOAP Fault Formatting changes
  app/controllers/oncore_endpoint_controller.rb
  app/views/wash_out/rpc/error.builder
Labels: MUSC, version 3.7.0

#2374 [SPARCForms]resend button color change
  app/helpers/surveyor/responses_helper.rb
Labels: LA CaTS, bug, version 3.7.0

#2375 check if line items in FULFILLMENT_DB only when fulfillment_contingen…
  app/helpers/service_calendar_helper.rb
Labels: LA CaTS, bug, version 3.7.0

#2376 SJ Fixing Service Cost Report
  app/lib/reports/service_pricing_report.rb
  app/models/service.rb
Labels: MUSC, bug, version 3.7.0

#2377 KG - Fix Reports Broken by Multiple IRB Changes
  app/lib/reports/protocols.rb
  app/lib/reports/service_requests.rb
  app/models/protocol.rb
  app/models/sub_service_request.rb
Labels: MUSC, bug, version 3.7.0

#2378 Jl - Synched line item delete bug
  app/controllers/dashboard/study_level_activities_controller.rb
  config/locales/dashboard.en.yml
Labels: MUSC, bug, version 3.7.0

#2380 KG - Protocols Report Add Back Default submitted_at Range
  app/lib/reports/protocols.rb
Labels: MUSC, bug, cherry-pick, version 3.7.0

#2385 Jl - Synch update then delete bug
  app/controllers/dashboard/sub_service_requests_controller.rb
Labels: MUSC, bug, cherry-pick, version 3.7.0
