Repository sparc-request/sparc-request, pull requests merged in 2020-04, with the labels that each got.

#2270 update messages subject column display[169276107]
  app/helpers/dashboard/notifications_helper.rb
  app/views/dashboard/notifications/index.json.jbuilder
Labels: LA CaTS, enhancement, version 3.7.0

#2264 KG - Admin Edit Subject Count Don't Change to Draft
  app/controllers/line_items_visits_controller.rb
Labels: MUSC, bug, version 3.7.0

#2265 KG - Max Subject Count Buttons
  app/assets/stylesheets/utilities.scss
  app/controllers/arms_controller.rb
  app/views/arms/_form.html.haml
  app/views/line_items_visits/_form.html.haml
  config/locales/en.yml
  spec/models/arm/validations_spec.rb
Labels: MUSC, enhancement, version 3.7.0

#2271 HH - Cache Available Permissible Values [#171868635]
  app/models/permissible_value.rb
Labels: MUSC, bug, version 3.7.0

#2272 KG - Add "All Protocols" Protocol Filter for General Users
  app/assets/javascripts/custom/bootstrap-custom.es6
  app/helpers/dashboard/protocols_helper.rb
  app/models/protocol.rb
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/dashboard/protocols/index.json.jbuilder
  config/locales/dashboard.en.yml
  spec/features/dashboard/protocols/index/filters/user_filters_with_all_protocols_radio_spec.rb
  spec/views/dashboard/protocol_filters/_filter_protocols_form.html.haml_spec.rb
Labels: MUSC, enhancement, version 3.7.0

#2251 KG - Fix Broken SubServiceRequest ssr_id Code
  app/controllers/service_requests_controller.rb
  app/lib/add_service.rb
  app/models/service_request.rb
  app/models/sub_service_request.rb
  db/migrate/20200311190154_fix_protocol_next_ssr_id.rb
  lib/tasks/clean_up_services.rake
  lib/tasks/merge_services.rake
  lib/tasks/move_service.rake
  spec/factories/sub_service_request.rb
  spec/features/dashboard/admin/admin_edits_service_calendar_fields_spec.rb
  spec/features/dashboard/forms/user_completes_form_spec.rb
  spec/features/dashboard/forms/user_edits_form_response_spec.rb
  spec/features/dashboard/forms/user_views_form_response_spec.rb
  spec/features/dashboard/protocols/index/filters/user_filters_with_my_admin_protocols_radio_spec.rb
  spec/features/dashboard/protocols/index/filters/user_filters_with_organization_dropdown_spec.rb
  spec/features/dashboard/protocols/index/filters/user_filters_with_owner_dropdown_spec.rb
  spec/features/dashboard/protocols/index/filters/user_filters_with_status_dropdown_spec.rb
  spec/features/proper/document_management/user_adds_document_spec.rb
  spec/features/proper/document_management/user_completes_form_spec.rb
  spec/features/proper/document_management/user_deletes_form_response_spec.rb
  spec/features/proper/service_details/user_edits_service_calendar_fields_spec.rb
  spec/features/surveyor/responses/user_filters_responses_spec.rb
  spec/lib/dashboard/service_calendars_spec.rb
  spec/lib/notifier_logic/ssr_deletion_emails_spec.rb
  spec/models/protocol/all_forms_completed_spec.rb
  spec/models/protocol/has_completed_forms_spec.rb
  spec/models/service_request/associated_forms_spec.rb
  spec/models/sub_service_request/distribute_surveys_spec.rb
  spec/models/sub_service_request/sub_service_request_spec.rb
Labels: MUSC, bug, version 3.7.0

#2273 KG - Improved Epic Interface Push Error Handling
  app/models/protocol.rb
  lib/tasks/send_to_epic.rake
Labels: MUSC, bug, version 3.7.0

#2275 KG - Fix Service Calendar "Consolidated Request" Alignment
  app/assets/stylesheets/service_calendar.scss
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_header.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_header.html.haml
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_max_total_direct_per_patient.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_max_total_per_patient.html.haml
  app/views/service_calendars/master_calendar/pppv/totals/_total_cost_per_study.html.haml
Labels: MUSC, bug, version 3.7.0

#2276 KG - SSR Resubmission-related Request Submission Bug
  app/models/service_request.rb
Labels: MUSC, bug, version 3.7.0

#2277 KG - Max Subject Count "Apply to All" Tooltip
  app/views/arms/_form.html.haml
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.7.0

#2283 SJ - Fixing IE bug with epic questions
  app/assets/javascripts/protocol_form.js.coffee
Labels: MUSC, bug, version 3.7.0

#2284 Jl - Historical protocol merge refactor
  app/controllers/dashboard/protocols_controller.rb
  app/helpers/dashboard/protocols_helper.rb
  app/models/protocol.rb
  app/views/dashboard/protocols/_table.html.haml
Labels: MUSC, version 3.7.0

#2278 KG - Remove "Get a Cost Estimate" Button / Default Status
  app/controllers/service_requests_controller.rb
  app/helpers/notifier_helper.rb
  app/lib/notifier_logic.rb
  app/mailers/notifier.rb
  app/views/notifier/_welcome.html.haml
  app/views/notifier/_welcome_for_submitted_status.html.haml
  app/views/service_requests/confirmation.html.haml
  app/views/service_requests/navigation/_footer.html.haml
  app/views/service_requests/navigation/_steps.html.haml
  config/application.yml.example
  config/defaults.json
  config/locales/en.yml
  config/locales/proper.en.yml
  config/navigation.yml
  config/routes.rb
  db/migrate/20200402195743_remove_get_a_cost_estimate_default.rb
  db/schema.rb
  habitat/sparc-request-base/default.toml
  lib/tasks/fix_past_status_data.rake
  spec/controllers/service_requests/get_obtain_research_pricing_spec.rb
  spec/features/proper/review/user_takes_system_satisfaction_survey_spec.rb
  spec/lib/notifier_logic/update_status_and_send_get_a_cost_estimate_email_spec.rb
  spec/mailers/notifier/get_a_cost_estimate_spec.rb
  spec/mailers/notifier/request_amendment_spec.rb
  spec/models/service_request/update_status_spec.rb
  spec/models/sub_service_request/formatted_status_spec.rb
  spec/models/sub_service_request/sub_service_request_spec.rb
  spec/models/sub_service_request/update_status_and_notify_spec.rb
  spec/support/emails/messages.rb
  spec/support/fixtures.rb
Labels: MUSC, enhancement, version 3.7.0

#2287 Enable Other Funding Status Options[#170883735]
  app/models/protocol.rb
  db/seeds/permissible_values/2.0.5/funding_statuses.csv
Labels: LA CaTS, enhancement, version 3.7.0

#2290 KG - Add Service Name Display For All Calendar Field Editing
  app/views/line_items/_form.html.haml
  app/views/line_items_visits/_form.html.haml
  app/views/visits/_form.html.haml
Labels: MUSC, enhancement, version 3.7.0

#2292 KG - Service Calendar Cell Wrapping
  app/assets/stylesheets/service_calendar.scss
  app/views/service_calendars/_quantity.html.haml
  app/views/service_calendars/_subject_count.html.haml
  app/views/service_calendars/_units_per_quantity.html.haml
Labels: MUSC, enhancement, version 3.7.0

#2296 KG - Random Spec Failures
  app/models/question.rb
  spec/features/surveyor/surveys/user_edits_question_fields_spec.rb
Labels: MUSC, refactors, specs, version 3.7.0

#2291 KG - Fix Duplicate SSR / Skipped SSR ID Bugs
  app/controllers/protocols_controller.rb
  app/models/protocol.rb
  app/models/service_request.rb
  app/models/sub_service_request.rb
  spec/lib/notifier_logic/update_ssrs_and_send_emails_spec.rb
  spec/models/identity_spec.rb
  spec/models/sub_service_request/sub_service_request_spec.rb
  spec/support/fixtures.rb
Labels: MUSC, bug, version 3.7.0

#2297 Jl - Protocol merge ssr ordering and new validations
  app/controllers/dashboard/protocol_merges_controller.rb
  app/lib/dashboard/fix_ssr_ids.rb
  config/locales/dashboard.en.yml
Labels: MUSC, refactors, version 3.7.0

#2299 Fix Survey Responses Resend Button Bugs
  app/controllers/surveyor/responses_controller.rb
  app/helpers/surveyor/responses_helper.rb
Labels: LA CaTS, bug, version 3.7.0

#2300 Jl - Inactive service display bug
  app/views/dashboard/sub_service_requests/_tabs.html.haml
Labels: MUSC, bug, version 3.7.0

#2301 KG - Service Request Resubmission Epic Queue Push Logic Change
  app/controllers/service_requests_controller.rb
  app/models/line_item.rb
  app/models/protocol.rb
  app/models/service_request.rb
  app/models/sub_service_request.rb
  spec/models/service_request/should_push_to_epic_spec.rb
  spec/support/settings.rb
Labels: MUSC, enhancement, version 3.7.0

#2308 SJ - Fix for phone format
  app/helpers/application_helper.rb
Labels: MUSC, bug, version 3.7.0

#2307 SJ - Adding "other" role details to users table
  app/helpers/associated_users_helper.rb
  app/views/associated_users/index.json.jbuilder
  app/views/dashboard/associated_users/index.json.jbuilder
Labels: MUSC, enhancement, version 3.7.0

#2306 SAW - OnCore SOAP Endpoint Changes
  app/controllers/oncore_endpoint_controller.rb
  app/views/wash_out/rpc/error.builder
  spec/controllers/oncore_endpoint_controller_spec.rb
  spec/support/oncore_endpoint_helper.rb
Labels: MUSC

#2312 SAW - OnCore Endpoint Removed Code with Typo
  app/controllers/oncore_endpoint_controller.rb
Labels: MUSC

#2309 KG - Fix Protocol Search Code When Search Term Blank
  app/models/protocol.rb
Labels: MUSC, bug, version 3.7.0

#2310 SAW - Add Description to Service/Org Searches
  app/assets/javascripts/catalog_manager/catalog.js.coffee
  app/controllers/search_controller.rb
Labels: MUSC, version 3.7.0

#2311 KG - Add Primary Contacts to Organization API
  app/api/v1/base.rb
  app/api/v1/entities/full.rb
  app/api/v1/entities/full_with_shallow_reflections.rb
  app/models/organization.rb
  app/views/catalogs/_primary_contacts.html.haml
Labels: MUSC, enhancement, version 3.7.0

#2313 add a hold_emails attrirbute to super users
  app/assets/javascripts/catalog_manager/form.js.coffee
  app/controllers/catalog_manager/super_users_controller.rb
  app/controllers/surveyor/responses_controller.rb
  app/views/catalog_manager/organizations/_user_rights_row.html.haml
  config/locales/catalog_manager.en.yml
  db/migrate/20200423153027_add_hold_emails_to_super_users.rb
Labels: LA CaTS, enhancement, version 3.7.0

#2317 'Not Funded' funding status related UI updates
  app/assets/javascripts/protocol_form.js.coffee
  app/views/protocols/_summary.html.haml
  app/views/protocols/view_details/_financial_information.html.haml
Labels: LA CaTS, enhancement, version 3.7.0

#2318 SJ - Fixing Submitted SR's
  lib/tasks/fix_submitted_srs.rake
Labels: MUSC, bug, version 3.7.0

#2305 Survey/Form Responses View Update [#16707638]
  app/controllers/surveyor/responses_controller.rb
  app/models/system_survey.rb
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/responses/index.json.jbuilder
Labels: LA CaTS, enhancement, version 3.7.0
