Repository sparc-request/sparc-request, pull requests merged in 2020-03, with the labels that each got.

#2218 KG - Organization Deep Link
  .travis.yml
  app/api/v1/base.rb
  app/api/v1/entities/full.rb
  app/api/v1/entities/full_with_shallow_reflections.rb
  app/api/v1/entities/shallow.rb
  app/controllers/service_requests_controller.rb
  app/models/organization.rb
  app/models/service.rb
  app/views/catalog_manager/organizations/_general_info_form.html.haml
  app/views/catalog_manager/services/_general_info_form.html.haml
  app/views/catalogs/_catalog_center.html.haml
  app/views/catalogs/accordion/_cores.html.haml
  app/views/catalogs/accordion/_institutions.html.haml
  app/views/catalogs/accordion/_providers.html.haml
  app/views/service_requests/catalog.html.haml
  config/locales/catalog_manager.en.yml
  config/routes.rb
  dotenv.example
Labels: MUSC, enhancement, version 3.7.0

#2242 KG - Calendar Bugs
  app/controllers/arms_controller.rb
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_header.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_header.html.haml
Labels: MUSC, bug, version 3.7.0

#2245 SAW - Added Timestamp to Epic SOAP Log
  lib/epic_interface.rb
Labels: MUSC, version 3.7.0

#2246 SAW - SPARCForms Filter Bug
  app/views/surveyor/responses/_filter_responses_form.html.haml
  app/views/surveyor/responses/_surveys_dropdown.html.haml
Labels: MUSC, bug, version 3.7.0

#2252 KG - Add Funding Lock
  app/views/protocols/form/_financial_information.html.haml
  config/locales/en.yml
Labels: MUSC, enhancement, version 3.7.0

#2260 HH - (SPARCRequest) Errors With lazy_load_ldap Enabled [#171888331]
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/concerns/protocols_controller_shared.rb
  app/controllers/search_controller.rb
  app/views/protocols/form/_protocol_information.html.haml
Labels: bug, version 3.7.0

#2262 Removes invalid xplat characters from file names
  spec/models/protocol/active_spec.rb
  spec/models/protocol/all_forms_completed_spec.rb
  spec/models/protocol/has_completed_forms_spec.rb
  spec/models/protocol/notify_remote_around_update_spec.rb
  spec/models/protocol/valid_spec.rb
  spec/models/service_request/has_associated_forms_spec.rb
  spec/models/sub_service_request/all_forms_completed_spec.rb
  spec/models/sub_service_request/form_completed_spec.rb
  spec/models/sub_service_request/has_completed_forms_spec.rb
Labels: bug, version 3.7.0

#2268 KG - RMID Validated Flag When RMID Removed
  app/helpers/protocols_helper.rb
  app/models/protocol.rb
Labels: MUSC, enhancement, version 3.7.0
