Repository sparc-request/sparc-request, pull requests merged in 2021-07, with the labels that each got.

#2726 Upgrade rails and dependencies to 5.2.4.6
  Gemfile
  Gemfile.lock
Labels: LA CaTS, dependencies, security, version 3.9.0

#2723 SRY - Fixing Admin Approval Checkboxes
  app/api/v1/entities/full.rb
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/models/sub_service_request.rb
  app/views/dashboard/sub_service_requests/details/_approvals.html.haml
  config/routes.rb
  db/migrate/20210629145042_remove_approval_columns_from_sub_service_request.rb
  spec/models/sub_service_request/update_status_and_notify_spec.rb
Labels: MUSC, version 3.9.0

#2730 SRY - Specs for admin approvals
  spec/controllers/dashboard/sub_service_requests/put_update_approval_spec.rb
  spec/models/sub_service_request/admin_approvals_spec.rb
Labels: MUSC, specs, version 3.9.0

#2727 Update SSR status right after SR submission while keeping email
  app/controllers/service_requests_controller.rb
  spec/controllers/service_requests/get_confirmation_spec.rb
Labels: LA CaTS, enhancement, version 3.9.0

#2732 SJ - Default Billing Changes
  app/controllers/concerns/protocols_controller_shared.rb
  app/controllers/protocols_controller.rb
  app/controllers/service_calendars_controller.rb
  app/helpers/application_helper.rb
  app/views/protocols/form/_protocol_billing_form.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_column.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_select_row.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_visit_input.html.haml
  db/migrate/20210723204302_change_all_research_billing_to_billing_type.rb
  spec/api/v1/protocols/get_protocol_spec.rb
  spec/api/v1/protocols/get_protocols_spec.rb
  spec/api/v1/protocols/get_protocols_with_ids_spec.rb
Labels: MUSC, bug, enhancement, refactors, version 3.9.0
