Repository sparc-request/sparc-request, pull requests merged in 2021-05, with the labels that each got.

#2689 SJ - Temp Fix for Protocol Search
  app/controllers/dashboard/protocols_controller.rb
Labels: MUSC, bug, version 3.9.0

#2688 Close the Edit Authorized User modal window
  app/views/dashboard/associated_users/update.js.coffee
Labels: LA CaTS, bug, version 3.9.0

#2690 SRY - Investigational Products Information Label Change
  config/locales/en.yml
Labels: MUSC, version 3.9.0

#2691 Exception and incorrect ssr fixes
  app/views/funding/services/documents.json.jbuilder
Labels: LA CaTS, bug, version 3.9.0

#2705 SRY - Oncore Push Date Sorting Bug Fix
  app/views/dashboard/oncore_records/index.html.haml
Labels: MUSC, version 3.9.0

#2699 SRY - Editing Date Processed and Date Completed Fields in Admin Edit
  app/models/line_item.rb
Labels: MUSC, version 3.9.0

#2710 SRY - Admin users able to search all protocols
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/dashboard/protocols/index.json.jbuilder
  spec/views/dashboard/protocol_filters/_filter_protocols_form.html.haml_spec.rb
Labels: MUSC, version 3.9.0

#2712 Fixing update project bug where a required field value is missing
  app/views/dashboard/protocols/update.js.coffee
  app/views/protocols/update.js.coffee
Labels: LA CaTS, bug, version 3.9.0
