Repository sparc-request/sparc-request, pull requests merged in 2021-01, with the labels that each got.

#2555 Added protocol merge email alert feature & a new column to display historical merge protocol ID into Protocols report
  app/controllers/dashboard/protocol_merges_controller.rb
  app/lib/reports/protocols.rb
  app/mailers/protocol_mailer.rb
  app/views/layouts/_header.html.haml
  app/views/protocol_mailer/_issue_contact.html.haml
  app/views/protocol_mailer/merge_protocols_email.html.haml
  config/locales/en.yml
Labels: LA CaTS, enhancement, version 3.9.0

#2567 service request should have a 'submitted' status when merging 2 proto…
  app/lib/dashboard/merge_srs.rb
Labels: LA CaTS, bug, version 3.9.0

#2591 SRY - Fixing program dropdown for inactive services
  app/views/catalog_manager/services/_general_info_form.html.haml
Labels: MUSC, version 3.9.0

#2596 SJ - Duplicate Dropdown Bug
  app/views/catalog_manager/services/_general_info_form.html.haml
  app/views/catalog_manager/services/reload_core_dropdown.js.coffee
Labels: MUSC, bug, version 3.9.0

#2574 Fix missing document organizations bug when share_all = 1
  app/controllers/funding/services_controller.rb
  app/views/funding/services/documents.json.jbuilder
Labels: LA CaTS, bug, version 3.9.0
