Repository sparc-request/sparc-request, pull requests merged in 2021-02, with the labels that each got.

#2613 Display Funding Status instead of Potential Funding Source in Study
  app/views/notifier/_protocol_information.html.haml
Labels: LA CaTS, bug, version 3.9.0

#2629 SAW - OnCore API Short Title Change
  app/lib/oncore_protocol.rb
Labels: MUSC, version 3.9.0

#2638 Jl - Hb Service Update Task Pricing Bug
  lib/tasks/update_hb_services.rake
Labels: MUSC, bug, version 3.9.0

#2639 SJ - LBB Flag for Users
  db/migrate/20210223212144_add_lbb_flag_to_identities.rb
Labels: MUSC, enhancement, version 3.9.0
