Repository sparc-request/sparc-request, pull requests merged in 2022-08, with the labels that each got.

#2924 SRY - Fixing reply from notification email link
  app/views/dashboard/messages/create.js.coffee
Labels: MUSC, v3.10.0

#2929 JL - Fix bug with dashboard merged protocol search
  app/controllers/dashboard/protocols_controller.rb
Labels: MUSC, version 3.10.0

#2930 SRY - Batch download additional changes
  app/assets/javascripts/documents.js.coffee
  app/views/dashboard/documents/index.json.jbuilder
  app/views/documents/_table.html.haml
  app/views/documents/index.json.jbuilder
Labels: MUSC, v3.10.0

#2931 Rails 5.2.8.1 security upgrade
  Gemfile
  Gemfile.lock
  config/application.rb
Labels: LA CaTS, security, v3.10.0

#2944 SRY - Fixing batch download issues
  app/controllers/documents_controller.rb
Labels: MUSC, version 3.10.0

#2945 GM - Update column labels on Cost Analysis report
  app/lib/cost_analysis/visit_table.rb
Labels: MUSC, version 3.10.0

#2946 JL - Update reserved status for certain permissible values
  db/seeds/permissible_values/2.0.5/funding_sources.csv
  db/seeds/permissible_values/2.0.5/funding_statuses.csv
  db/seeds/permissible_values/2.0.5/potential_funding_sources.csv
  db/seeds/permissible_values/2.0.5/proxy_rights.csv
  lib/tasks/update_permissible_values.rake
Labels: MUSC, version 3.10.0, feature

#2943 SRY - Fixing Protocol Merge Issues
  app/controllers/dashboard/protocol_merges_controller.rb
Labels: MUSC, version 3.10.0

#2925 Add configurable demographics attributes to profile
  app/assets/javascripts/identities.js.coffee
  app/controllers/admin/identities_controller.rb
  app/controllers/identities/registrations_controller.rb
  app/lib/reports/unique_pi.rb
  app/models/identity.rb
  app/models/race.rb
  app/views/admin/identities/_form.html.haml
  app/views/admin/identities/_show.html.haml
  app/views/devise/registrations/_profile_form.html.haml
  app/views/devise/registrations/edit.html.haml
  app/views/devise/registrations/update.js.coffee
  config/defaults.json
  config/locales/devise.en.yml
  config/locales/en.yml
  db/migrate/20140714153033_add_demographic_info_to_identities.rb
  db/migrate/20150615180639_add_is_hispanic_to_identities.rb
  db/migrate/20220527172623_change_is_hispanic_column_in_identities.rb
  db/migrate/20220607182543_add_other_gender_to_identity.rb
  db/migrate/20220607191441_create_races.rb
  db/schema.rb
  db/seeds/permissible_values/2.0.5/age_groups.csv
  db/seeds/permissible_values/2.0.5/ethnicities.csv
  db/seeds/permissible_values/2.0.5/genders.csv
  db/seeds/permissible_values/2.0.5/interaction_subjects.csv
  db/seeds/permissible_values/2.0.5/interaction_types.csv
  db/seeds/permissible_values/2.0.5/races.csv
  db/seeds/permissible_values/README.md
Labels: enhancement, LA CaTS, version 3.10.0
