Repository sparc-request/sparc-request, pull requests merged in 2022-10, with the labels that each got.

#2992 Quick bug fix where gender_other field not be shown when gender is removed from demographic setting
  app/views/admin/identities/_form.html.haml
  app/views/devise/registrations/_profile_form.html.haml
Labels: bug, LA CaTS, version 3.10.0

#2979 GM - Change language and default radio
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/service_requests/add_service.js.coffee
  config/locales/proper.en.yml
Labels: MUSC, version 3.10.0, operational committee approved

#2982 JV - Max Length Validation Added to Protocol attribute 'short_title'
  app/models/protocol.rb
  db/schema.rb
Labels: bug, MUSC, version 3.10.0

#3000 GM - Cost analysis report - update column titles on clinical services with visits
  app/lib/cost_analysis/visit_table.rb
Labels: version 3.10.0

#3001 JL - Combine Funding Source and Potential Funding Source
  app/api/v1/entities/full.rb
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/concerns/protocols_controller_shared.rb
  app/lib/reports/protocols.rb
  app/models/permissible_value.rb
  app/models/protocol.rb
  app/views/protocols/_summary.html.haml
  app/views/protocols/form/_financial_information.html.haml
  app/views/protocols/view_details/_financial_information.html.haml
  config/locales/en.yml
  db/migrate/20221005201755_remove_potential_funding_source_from_protocols.rb
  db/schema.rb
  db/seeds/permissible_values/2.0.5/potential_funding_sources.csv
  doc/multi_institutional_documentation.md
  lib/epic_interface.rb
  lib/tasks/delete_potential_funding_values.rake
  lib/tasks/import_protocols.rake
  lib/tasks/update_permissible_values.rake
  spec/api/v1/protocols/get_protocol_spec.rb
  spec/api/v1/protocols/get_protocols_spec.rb
  spec/api/v1/protocols/get_protocols_with_ids_spec.rb
  spec/extensions/epic_interface_spec.rb
  spec/factories/protocol.rb
  spec/models/protocol/funding_source_based_on_status_spec.rb
  spec/support/permissible_values.rb
  spec/views/protocols/_summary.html.haml_spec.rb
Labels: MUSC, version 3.10.0, feature

#3007 GM - Filter protocols default radio fix
  app/controllers/dashboard/protocols_controller.rb
  app/views/dashboard/protocol_filters/_filter_protocols_form.html.haml
  app/views/service_requests/add_service.js.coffee
Labels: version 3.10.0

#3009 GM - Multi-select documents checkbox issue fix
  app/views/documents/_table.html.haml
  spec/helpers/documents_helper_spec.rb
Labels: version 3.10.0

#3012 JL - Human subjects driven logic for epic questions bug
  app/assets/javascripts/protocol_form.js.coffee
  spec/features/dashboard/protocols/new/user_selects_publish_in_epic_spec.rb
  spec/features/proper/protocol/protocols/user_selects_publish_in_epic_spec.rb
Labels: bug, MUSC, version 3.10.0

#3017 Fix SPARCFunding Document Download export button bug with refactors
  app/assets/javascripts/funding/documents.js.coffee
  app/controllers/funding/services_controller.rb
  app/views/funding/services/_documents.html.haml
  app/views/funding/services/_loi_table.html.haml
  app/views/funding/services/_table.html.haml
Labels: bug, LA CaTS, version 3.10.0
