Repository sparc-request/sparc-request, pull requests merged in 2022-05, with the labels that each got.

#2891 SJ - Fixing Travis
  .travis.yml
  lib/tasks/migrate_ids_to_bigint.rake
Labels: bug, MUSC, version 3.10.0

#2885 Add the 'By' and 'Date' columns to the Form Submissions table on SPAR…
  app/views/forms/_table.html.haml
  app/views/forms/index.json.jbuilder
  config/locales/en.yml
Labels: enhancement, LA CaTS, version 3.10.0

#2888 SRY - Protocol merge to include non master pro number
  app/controllers/dashboard/protocol_merges_controller.rb
Labels: MUSC, version 3.10.0

#2889 Bump rails and dependences from 5.2.6.3 to 5.2.8
  Gemfile
  Gemfile.lock
Labels: LA CaTS, security, v3.10.0

#2886 SRY - Allowing integer decimals
  app/models/question_response.rb
  app/views/surveyor/responses/form/form_partials/_number_form_partial.html.haml
Labels: MUSC, version 3.10.0

#2893 SRY - Adding manually fold display of ssr
  app/views/service_calendars/master_calendar/otf/_otf_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/billing_strategy/_billing_strategy_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/calendar/_calendar_line_items.html.haml
  app/views/service_calendars/master_calendar/pppv/template/_template_line_items.html.haml
Labels: MUSC, version 3.10.0

#2892 SRY - Adding back and forth arrows to edit billing quantities window
  app/assets/javascripts/service_calendar.js.coffee
  app/assets/stylesheets/service_calendar.scss
  app/controllers/visits_controller.rb
  app/models/visit.rb
  app/views/visits/_form.html.haml
  app/views/visits/edit.js.coffee
  app/views/visits/update.js.coffee
Labels: MUSC, version 3.10.0
