Repository sparc-request/sparc-request, pull requests merged in 2022-09, with the labels that each got.

#2960 JL - Ability to copy an arm
  app/controllers/arms_controller.rb
  app/helpers/arms_helper.rb
  app/services/application_service.rb
  app/services/arm_copier.rb
  app/views/arms/_form.html.haml
  app/views/arms/copy.js.coffee
  config/locales/en.yml
  config/routes.rb
  spec/services/arm_copier_spec.rb
Labels: MUSC, version 3.10.0, feature

#2963 SRY - Additional changes to batch document access
  app/assets/javascripts/documents.js.coffee
  app/helpers/documents_helper.rb
  app/views/dashboard/documents/create.js.coffee
  app/views/dashboard/documents/destroy.js.coffee
  app/views/dashboard/documents/update.js.coffee
  app/views/documents/_table_form.html.haml
  app/views/documents/create.js.coffee
  app/views/documents/destroy.js.coffee
  app/views/documents/update.js.coffee
  config/locales/en.yml
Labels: MUSC, version 3.10.0

#2947 SRY - Updating Epic question and notes
  config/constants.yml
  lib/tasks/study_type_questions_version_3_text_change.rake
  spec/features/dashboard/protocols/new/user_selects_publish_in_epic_spec.rb
  spec/features/proper/protocol/protocols/user_selects_publish_in_epic_spec.rb
Labels: MUSC, version 3.10.0

#2970 JL - Add optional reserved column for permissible values table
  app/views/admin/permissible_values/_table.html.haml
  app/views/admin/permissible_values/index.json.jbuilder
Labels: enhancement, MUSC, version 3.10.0

#2971 JL - Line items visit subject count not correct when copying an arm
  app/services/arm_copier.rb
Labels: bug, MUSC, version 3.10.0

#2974 GM - Update column labels on Cost Analysis report
  app/lib/cost_analysis/visit_table.rb
Labels: MUSC, version 3.10.0

#2976 JL - Delete surveyor 'user_edits_options_field' feature test
  spec/features/surveyor/surveys/user_edits_option_fields_spec.rb
Labels: specs, MUSC, version 3.10.0, chore

#2977 Fix protocol merge affiliation bug and create rake task to clean up affiliation duplicate
  app/controllers/dashboard/protocol_merges_controller.rb
  lib/tasks/remove_duplicate_affiliations.rake
Labels: bug, LA CaTS, version 3.10.0

#2980 modify identity display_gender method
  app/models/identity.rb
Labels: bug, LA CaTS, version 3.10.0

#2983 JL - Place ssr back into draft status if an arm is copied
  app/services/arm_copier.rb
Labels: enhancement, MUSC, version 3.10.0

#2981 JL - Change document version column to be optional
  app/views/documents/_table.html.haml
Labels: bug, MUSC, version 3.10.0
