Repository sparc-request/sparc-request, pull requests merged in 2023-05, with the labels that each got.

#3095 Fixing Coverage Analysis Button Bug
  app/views/service_requests/coverage_analysis.xlsx.axlsx
Labels: bug, LA CaTS, v3.11.0

#3099 Add Optional Services Column On Service Requests Report
  app/lib/reports/service_requests.rb
  app/models/sub_service_request.rb
Labels: enhancement, LA CaTS, v3.11.0

#3102 Fix Bulk Download Documents and Edit Access bugs
  app/controllers/documents_controller.rb
  app/helpers/documents_helper.rb
  app/views/dashboard/documents/index.json.jbuilder
  spec/helpers/documents_helper_spec.rb
Labels: bug, LA CaTS, v3.11.0

#3111 Only open SPARCCatalog module in new tab
  app/helpers/application_helper.rb
Labels: LA CaTS, feature, v3.11.0

#3109 JV - Fix / Validation to Prevent Document Creation without Attachment
  app/models/document.rb
  spec/features/dashboard/documents/user_deletes_document_spec.rb
  spec/features/dashboard/documents/user_edits_document_spec.rb
  spec/features/proper/document_management/user_deletes_document_spec.rb
  spec/features/proper/document_management/user_edits_document_spec.rb
  spec/helpers/documents_helper_spec.rb
  spec/lib/document_remover_spec.rb
  spec/models/document_spec.rb
Labels: MUSC, v3.11.0

#3113 Fixing protocol merge issue
  app/controllers/dashboard/protocol_merges_controller.rb
  app/lib/dashboard/fix_ssr_ids.rb
Labels: bug, LA CaTS, version 3.11.0

#3115 Minor opening sparc modules in new tab changes
  app/helpers/application_helper.rb
Labels: enhancement, LA CaTS, feature, version 3.11.0

#3117 Update Service Requests report column name
  app/lib/reports/service_requests.rb
Labels: LA CaTS, version 3.11.0

#3120 JV - Funding Status Column Added to Protocols Report
  app/lib/reports/protocols.rb
Labels: MUSC, operational committee approved, version 3.11.0

#3116 Add Regional Health Network (RHN) Organization options for user profiles at MUSC
  app/controllers/associated_users_controller.rb
  app/models/professional_organization.rb
  lib/tasks/add_rhn_to_professional_organizations.rake
Labels: version 3.11.0
