Repository sparc-request/sparc-request, pull requests merged in 2023-01, with the labels that each got.

#3046 SJ - Adding fields to pricing report
  app/lib/reports/service_pricing_report.rb
Labels: enhancement, MUSC, version 3.10.1

#3054 Fixing undefined method for NilClass bug- sparc settings
  app/helpers/admin/settings_helper.rb
Labels: bug, LA CaTS, version 3.10.1

#3056 Unable to change funding status from 'Not Funded' to others bug fix
  app/assets/javascripts/protocol_form.js.coffee
Labels: bug, LA CaTS, version 3.10.1

#3073 YW-Added Funding Status to protocol summary
  app/views/protocols/_summary.html.haml
Labels: enhancement, LA CaTS, version 3.10.1

#3076 GM - Fix 'Close' button in messages inbox
  app/views/dashboard/messages/_index.html.haml
Labels: version 3.10.1

#3077 Fix SPARCFunding Document Download error
  app/helpers/funding/documents_helper.rb
Labels: bug, LA CaTS, version 3.10.1

#3092 Fix undefined method 'humanize' for ActiveStorage::Filename instance error
  app/controllers/funding/services_controller.rb
Labels: bug, LA CaTS, version 3.10.1

#3093 Fix a Funding Document Download table export button bug
  app/controllers/funding/services_controller.rb
Labels: bug, LA CaTS, version 3.10.1
