Repository sparc-request/sparc-request, pull requests merged in 2023-10, with the labels that each got.

#3165 EPIC Q1 & notes display for non-EPIC studies
  app/assets/javascripts/protocol_form.js.coffee
  app/views/protocols/view_details/_protocol_information.html.haml
Labels: v3.12.0

#3173 JV - SRID Column Sorts Numerically and Appropriately Considers Dashes as Decimals
  app/assets/javascripts/utilities.js.coffee
Labels: bug, MUSC, v3.12.0

#3176 Ie resend surveys notifications update
  app/models/response.rb
  app/models/sub_service_request.rb
  app/views/survey_notification/service_survey.html.haml
  spec/features/proper/document_management/user_deletes_form_response_spec.rb
  spec/features/surveyor/surveys/user_takes_survey_spec.rb
  spec/models/sub_service_request/distribute_surveys_spec.rb
  spec/models/sub_service_request/form_completed_spec.rb
  spec/models/sub_service_request/forms_to_complete_spec.rb
Labels: version 3.12.0

#3178 Recent Submitted By - New Feature
  app/controllers/dashboard/sub_service_requests_controller.rb
  app/lib/remove_service.rb
  app/lib/reports/service_requests.rb
  app/models/sub_service_request.rb
  app/views/notifier/_audit_action.html.haml
  app/views/notifier/_audit_edited_ssrs.html.haml
  app/views/notifier/_audit_new_or_destroyed_ssr.html.haml
  app/views/notifier/_deleted_srid_information.html.haml
  config/locales/en.yml
  db/migrate/20231016154342_add_recent_submitted_by_to_ssr.rb
  db/schema.rb
  spec/api/v1/sub_service_requests/get_sub_service_request_spec.rb
  spec/api/v1/sub_service_requests/get_sub_service_requests_spec.rb
  spec/api/v1/sub_service_requests/get_sub_service_requests_with_ids_spec.rb
  spec/lib/notifier_logic/update_ssrs_and_send_emails_spec.rb
Labels: LA CaTS, feature, version 3.12.0
