Repository sparc-request/sparc-request, pull requests merged in 2023-11, with the labels that each got.

#3180 Fix study_type_questions display issues
  app/assets/javascripts/protocol_form.js.coffee
  app/helpers/protocols_helper.rb
  app/views/protocols/form/_study_type_questions.html.haml
  app/views/protocols/view_details/_protocol_information.html.haml
Labels: version 3.12.0

#3181 Update Milestone 'Site Level' Field Names
  config/locales/en.yml
Labels: version 3.12.0

#3182 Remove email submission data when split/notify is disabled
  app/controllers/catalog_manager/organizations_controller.rb
Labels: version 3.12.0

#3184 JV - Make Protocol Merge Modal Fields Searchable
  app/controllers/search_controller.rb
  app/models/protocol.rb
  app/views/dashboard/protocol_merges/new.js.coffee
  config/routes.rb
Labels: MUSC, operational committee approved, v3.12.0

#3188 removed stray exclamation point
  app/models/sub_service_request.rb
Labels: version 3.12.0

#3185 Fix visit group popover bug
  app/views/visit_groups/edit.js.coffee
Labels: version 3.12.0

#3190 syntax fix
  app/views/notifier/_audit_edited_ssrs.html.haml
Labels: bug, LA CaTS, version 3.12.0

#3192 JV - Stylized Confirmation Prompt for Archiving and Unarchiving Protocols
  app/helpers/protocols_helper.rb
  config/locales/en.yml
  spec/features/dashboard/protocols/show/user_archives_protocol_spec.rb
Labels: MUSC, operational committee approved, v3.12.0

#3193 Add `additional_funding_sources`
  app/assets/javascripts/additional_funding_sources.js.coffee
  app/assets/javascripts/application.js
  app/assets/javascripts/protocol_form.js.coffee
  app/assets/stylesheets/scaffolds.scss
  app/controllers/additional_funding_sources_controller.rb
  app/controllers/concerns/protocols_controller_shared.rb
  app/models/additional_funding_source.rb
  app/models/protocol.rb
  app/models/study.rb
  app/views/additional_funding_sources/_additional_funding_source.html.haml
  app/views/additional_funding_sources/_destroy.html.haml
  app/views/additional_funding_sources/_form.html.haml
  app/views/additional_funding_sources/_new_additional_funding_source.html.haml
  app/views/additional_funding_sources/create.js.coffee
  app/views/additional_funding_sources/destroy.js.coffee
  app/views/additional_funding_sources/edit.js.coffee
  app/views/additional_funding_sources/new.js.coffee
  app/views/additional_funding_sources/update.js.coffee
  app/views/protocols/form/_financial_information.html.haml
  app/views/protocols/view_details/_additional_funding_sources.html.haml
  app/views/protocols/view_details/_financial_information.html.haml
  config/defaults.json
  config/locales/en.yml
  config/routes.rb
  db/migrate/20231115180501_create_additional_funding_sources.rb
  db/schema.rb
  spec/factories/additional_funding_sources.rb
  spec/models/additional_funding_source_spec.rb
  spec/models/external_organization_spec.rb
  spec/requests/additional_funding_sources_spec.rb
  spec/routing/additional_funding_sources_routing_spec.rb
  spec/views/additional_funding_sources/_additional_funding_source.html.haml_spec.rb
Labels: version 3.12.0

#3197 Epic study type questions not consistently displaying
  app/assets/javascripts/protocol_form.js.coffee
  spec/features/dashboard/protocols/edit/user_edits_confidentiality_epic_questions.rb
Labels: version 3.12.0

#3201 JV - Ability to Edit User Login in SPARC Admin and Toggle Off/On
  app/controllers/admin/identities_controller.rb
  app/models/identity.rb
  app/views/admin/identities/_form.html.haml
  app/views/admin/identities/_table.html.haml
  app/views/admin/identities/index.json.jbuilder
  config/defaults.json
Labels: MUSC, operational committee approved, v3.12.0
