Repository sparc-request/sparc-request, pull requests merged in 2023-12, with the labels that each got.

#3204 Add additional_funding_sources setting and set it to true
  lib/tasks/add_setting_for_additional_funding_sources.rake
Labels: version 3.12.0

#3200 updated irb assoc rmid function
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/concerns/protocols_controller_shared.rb
  app/controllers/irb_records_controller.rb
  app/models/irb_record.rb
  app/views/irb_records/_irb_record.html.haml
  app/views/irb_records/destroy.js.coffee
  app/views/protocols/validate_rmid.js.coffee
  db/migrate/20231113124044_add_rmid_id_to_irb_records.rb
  db/schema.rb
  spec/api/v1/irb_records/get_irb_record_spec.rb
  spec/api/v1/irb_records/get_irb_records_spec.rb
  spec/api/v1/irb_records/get_irb_records_with_ids_spec.rb
  spec/factories/irb_records.rb
Labels: v3.12.0

#3206 Fix `study_type_questions` display issues
  app/assets/javascripts/protocol_form.js.coffee
  app/helpers/protocols_helper.rb
  app/views/protocols/view_details/_protocol_information.html.haml
Labels: version 3.12.0

#3210 Fix `additional_funding_sources`
  app/api/v1/entities/full.rb
  app/assets/javascripts/protocol_form.js.coffee
  app/controllers/additional_funding_sources_controller.rb
  app/controllers/concerns/protocols_controller_shared.rb
  app/views/additional_funding_sources/_additional_funding_source.html.haml
  app/views/additional_funding_sources/edit.js.coffee
  app/views/protocols/form/_financial_information.html.haml
  app/views/protocols/view_details/_additional_funding_sources.html.haml
  app/views/protocols/view_details/_financial_information.html.haml
  config/locales/en.yml
  config/routes.rb
  db/migrate/20231206122238_add_additional_funding_sources_flag_to_protocols.rb
  db/schema.rb
Labels: version 3.12.0

#3218 fix typo
  app/views/pages/_draft_requests_modal.haml
Labels: bug, LA CaTS, version 3.12.0

#3217 Fix `additional_funding_sources`
  app/models/additional_funding_source.rb
Labels: version 3.12.0

#3220 Fix validation msg
  app/views/additional_funding_sources/_form.html.haml
  app/views/additional_funding_sources/update.js.coffee
Labels: version 3.12.0
