Repository sparc-request/sparc-request, pull requests merged in 2025-04, with the labels that each got.

#3251 Document uploaded bug in SPARCFunding
  app/views/funding/services/documents.json.jbuilder
Labels: bug, LA CaTS, version 3.13.0

#3253 JV - SSR Admin Edit Patch (SPOSDEV-1183)
  Dockerfile
  app/assets/javascripts/dashboard/sub_service_requests.js.coffee
  docker-compose.yml.example
Labels: MUSC, cherry-pick, version 3.13.0

#3254 JV - Document File Type Cleanup (SPOSDEV-1178)
  app/models/document.rb
Labels: MUSC, version 3.13.0
