Repository sparc-request/sparc-request, pull requests merged in 2025-03, with the labels that each got.

#3248 JV - Ruby 3 Bug Fixes (v2)
  app/models/document.rb
  app/views/surveyor/responses/create.js.coffee
  config/initializers/01_obis_setup.rb
  config/initializers/audit_trail.rb
  config/initializers/mail_send_interceptor.rb
Labels: MUSC, version 3.13.0

#3249 JV - MS Teams Integration for delayed_job_monitor Rake Task
  Gemfile
  Gemfile.lock
  config/defaults.json
  db/migrate/20250324182446_add_teams_webhook_setting.rb
  db/schema.rb
  lib/tasks/delayed_job_monitor.rake
Labels: MUSC, chore, version 3.13.0

#3245 fix remove service bug
  app/lib/remove_service.rb
Labels: bug, LA CaTS, version 3.13.0

#3246 fix for Documents table Uploaded column bug
  app/views/dashboard/documents/index.json.jbuilder
  app/views/documents/_table.html.haml
  app/views/documents/index.json.jbuilder
  config/locales/en.yml
Labels: bug, LA CaTS, version 3.13.0
